Posthog / UUID Integration
tahowallet/extension pull request #2384
Opened 2022-10-05 14:12 UTC by zuuring

This pull request adds a new analytics system powered by Posthog which checks if a UUID is stored in browser from Tally website. If analytics is enabled by user, Posthog events will fire.

Any posthog event can be created by simply

`import { posthogEvent } from "../../../background/services/analytics/posthog"`

and using the function `posthogEvent("Put your event title here");`

2022-10-05 15:07 UTC, greg-nagy requested changes
Wow, I am excited to see this land ✨🤩

Left some initial thoughts after a quick glance.

2022-10-05 15:07 UTC, greg-nagy commented on background/services/analytics/posthog.ts
> +function getCookie(name: string)
We have a solution in the extension that solves the same problem but without the need for cookies. I will dig it up for reference in a bit.

2022-10-05 15:12 UTC, zuuring commented on package.json
> +    "uuid": "^9.0.0",
Thanks for your comments! Using this lib to easily be able to generate UUIDs on the website. However I think it can be totally removed from the extension as it's only needed on the website facing portion of the implementation :)

2022-10-05 16:08 UTC, Shadowfiend commented
Oho it is time! Got a few notes from looking through, but excited to see this take shape :)

Few big setup things:
- Please make sure you're using yarn for package management. This PR commits a `package-lock.json` file—if you can, please update that commit (https://github.com/tallycash/extension/blob/244c2a092f60e19ae6edf52979185dbff735c4fd/package-lock.json) via rebase to drop the file entirely from history.
- Please make sure you've set up pre-commit hooks (e.g. https://github.com/tallycash/extension/pull/2384/files#diff-bb2ba232569016c28a3e1afeb301ce20420881034e715b0c87f88c6fd5db410cR1293 was probably not hit by the linter).

Instructions for both of these are in the README, under [Quickstart](https://github.com/tallycash/extension#quickstart) and [installing pre-commit hooks](https://github.com/tallycash/extension#installing-pre-commit-hooks).

Some additional notes:
- I suggest keeping this PR as a draft until it's ready to merge (I'm assuming that isn't the case now since the uninstall URL is pointed to localhost:8000, but could be wrong!). Another thing that would be good to figure out before considering this ready to merge is how we're going to handle the API key on dev builds vs production builds, if we want to try to differentiate—as well as whether we should accept a blank key for local builds/the public default value, or if we should instead have a specific key that's flagged accordingly in Posthog.
- I would suggest putting the analytics behind a feature flag for now so it can be developed across multiple PRs and tested easily by the team, see below.
- When the demo is satisfactory and it's time to move to merging stuff, I suggest splitting this up into multiple PRs, in particular one introducing the feature flag + service stuff around analytics, and separate PR(s) to add actual tracking.
- `service/analytics` is probably not appropriate if we're not actually setting up an analytics service class. I think the correct architectural spot to put this is to funnel analytics via redux async thunk to the telemetry service, and have the telemetry service handle calls to Posthog—but that doesn't really need to be a blocker. We may also probably want to push stuff into Posthog from e.g. the internal Ethereum provider in certain cases.

2022-10-05 16:16 UTC, greg-nagy commented
> I think the correct architectural spot to put this is to funnel analytics via redux async thunk to the telemetry service, and have the telemetry service handle calls to Posthog—but that doesn't really need to be a blocker. We may also probably want to push stuff into Posthog from e.g. the internal Ethereum provider in certain cases.

The original idea as a first step was to put the trigger into the react components, because we wanted to measure weekly active users, so the analytics data can be accurate and not be distorted by failing redux migrations or anything that happens between the UI and the background. Otoh adding wallet and removing event could be put anywhere else.

2022-10-05 16:23 UTC, 0xDaedalus commented on background/lib/posthog.ts
> +    console.log("data: ", JSON.stringify(result, null, 4))
I assume this is here for debugging purposes - we'll probably want to remove this

2022-10-05 16:23 UTC, 0xDaedalus commented on manifest/manifest.json
> +  "permissions": ["alarms", "storage", "unlimitedStorage", "activeTab", "cookies", "storage", "<all_urls>"],
duplicate `storage` permission here

2022-10-05 16:26 UTC, 0xDaedalus commented on package.json
> +    "@types/uuid": "^8.3.4",
I believe this is left-over from when the `uuid` library was in use.

2022-10-05 17:02 UTC, greg-nagy commented on background/lib/posthog.ts
> +    console.log("data: ", JSON.stringify(result, null, 4))
We should not have `console.log`s in the code at all, but I think this will be fixed with turning on the precommit hook.

2022-10-05 17:25 UTC, zuuring commented on background/lib/posthog.ts
> +    console.log("data: ", JSON.stringify(result, null, 4))
Removed all console logging for debugging!

2022-10-05 17:28 UTC, zuuring commented on background/lib/posthog.ts
> +          data:  "This adds posthog events to Tally extension",
For the `data:` entry? I was actually wondering the same! Would likely be useful for future posthog logging events. :)

2022-10-05 17:34 UTC, zuuring commented on background/lib/posthog.ts
> +export async function createEvent(eventName:string, userID:string): Promise<HogResponse> {
Thanks for your comments on this! Going to relay to @puppycodes as we spoke about the possibility of setting up a posthog instance which will also remove our reliance on firing the event based on the analytics service.

2022-10-06 14:08 UTC, zuuring commented
> Oho it is time! Got a few notes from looking through, but excited to see this take shape :)
> 
> Few big setup things:
> 
> * Please make sure you're using yarn for package management. This PR commits a `package-lock.json` file—if you can, please update that commit (https://github.com/tallycash/extension/blob/244c2a092f60e19ae6edf52979185dbff735c4fd/package-lock.json) via rebase to drop the file entirely from history.
> * Please make sure you've set up pre-commit hooks (e.g. https://github.com/tallycash/extension/pull/2384/files#diff-bb2ba232569016c28a3e1afeb301ce20420881034e715b0c87f88c6fd5db410cR1293 was probably not hit by the linter).
> 
> Instructions for both of these are in the README, under [Quickstart](https://github.com/tallycash/extension#quickstart) and [installing pre-commit hooks](https://github.com/tallycash/extension#installing-pre-commit-hooks).
> 
> Some additional notes:
> 
> * I suggest keeping this PR as a draft until it's ready to merge (I'm assuming that isn't the case now since the uninstall URL is pointed to localhost:8000, but could be wrong!). Another thing that would be good to figure out before considering this ready to merge is how we're going to handle the API key on dev builds vs production builds, if we want to try to differentiate—as well as whether we should accept a blank key for local builds/the public default value, or if we should instead have a specific key that's flagged accordingly in Posthog.
> * I would suggest putting the analytics behind a feature flag for now so it can be developed across multiple PRs and tested easily by the team, see below.
> * When the demo is satisfactory and it's time to move to merging stuff, I suggest splitting this up into multiple PRs, in particular one introducing the feature flag + service stuff around analytics, and separate PR(s) to add actual tracking.
> * `service/analytics` is probably not appropriate if we're not actually setting up an analytics service class. I think the correct architectural spot to put this is to funnel analytics via redux async thunk to the telemetry service, and have the telemetry service handle calls to Posthog—but that doesn't really need to be a blocker. We may also probably want to push stuff into Posthog from e.g. the internal Ethereum provider in certain cases.
> 
> EDIT to add: the `yarn.lock` updates also look weird. Not sure what that's from, but probably worth checking out the lockfile from before adding the uuid types dependency, then `yarn install`ing at the project root again to make sure the changes are good.

Thank you so much for the extensive feedback on this! I have now pushed a few new commits which resolve all the errors and pass pre-commit checks. Which involved some refactoring. Now onto feature flags!

2022-10-12 09:37 UTC, zuuring commented
I have just pushed a new commit which adds Uninstall browser hook event, so there is no need to forward to a webpage at the moment.

2022-10-13 13:37 UTC, Shadowfiend commented
> The original idea as a first step was to put the trigger into the react components, because we wanted to measure weekly active users, so the analytics data can be accurate and not be distorted by failing redux migrations or anything that happens between the UI and the background.

I'm not sure what else could happen between the UI and background, but it seems like being given warning of a failing redux migration by our analytics would be a good thing, not a bad one. I don't think it's the end of the world to start with these direct calls, but I do think the correct *end state* is to move to funnel all of them through redux actions.

IMO we can find reasons to make exceptions for almost anything to work outside of the core data flow we have established through redux, but then we end up with 10 ways for data to actually get processed and explode complexity—that's what I'm pushing to avoid here. To do that we need to avoid skipping that data flow unless there are specific, compelling, and fairly critical reasons to do so (think user safety-level stuff). If this were some sort of security signal that we needed to make it out at all costs, I think it would make sense, but in this context I would argue the reasons don't rise to that level.

Another thing to note here is that we can attach events to clicks (e.g. the wallet added event) or to actual actions (e.g. when a new keyring is actually added to the background, when a new Ledger is added, etc). If we're handling those events in two different ways, it becomes more difficult to find what events are kicked off where, it reduces our ability to handle the events locally for additional purposes. One quick example of where we might want to process locally is to send information about whether a flow was finished without pushing identifying information to the server, vs letting the server correlate using a unique id that it's aware of.

2022-10-13 18:21 UTC, greg-nagy requested changes
the PR does not work in it's current form 

let's move this back to draft and go through it as part of your onboarding. There is much here to unfold and it's not efficient to do this in PR reviews.

2022-10-13 18:21 UTC, greg-nagy commented on background/lib/posthog.ts
> +export const { POSTHOG_API_KEY } = process.env.POSTHOG_API_KEY
You don't need to export this variable, and here you are trying to destructure a string that will fail.

2022-10-13 18:21 UTC, greg-nagy commented on manifest/manifest.json
> +    "cookies",
I couldn't make this work with cookies. I always got `Unchecked runtime.lastError: No host permissions for cookies at url: "https://tally.cash/".` 

We might need to test this a bit more.

2023-04-14 15:38 UTC, Shadowfiend commented
We ended up pulling work from this into a few other places, and Posthog is now integrated into the wallet behind user opt-in, etc. Closing out!

2023-04-14 15:38 UTC, closed without merging