Add manifest v3 feature
tahowallet/extension pull request #2837
Opened 2023-01-04 04:16 UTC by aurelsziebert

Closes #2827

Makes possible to use V3 version of the manifest file.

Note that the project is broken with this feature on, because there are a few necessary changes in order to fulfil the migration from V2 to V3, what is out of the scope of this PR.

These changes are listed in issue #2694, and will be shipped in further PRs soon.

## To test

- [ ] Put `SUPPORT_MANIFEST_V3=true` into your .env file.

2023-01-06 07:34 UTC, hyphenized requested changes
Hi @aurelsziebert, thank you so much for jumping into this! Left you a couple of comments

2023-01-06 07:34 UTC, hyphenized commented on webpack.config.ts
> +                }
I think that rather than dropping the base file if an override is present, we could get rid of these extra checks if we had two base files (e.g. `manifest.v2.json` & `manifest.v3.json`) and changed the base prefix (currently `manifest`) depending whether `SUPPORT_MANIFEST_V3` is enabled or not.

We'd then have something like the following:

- `manifest.v3.json`
- `manifest.v3.chrome.json`
- `manifest.v3.development.json`
- `manifest.v2.json`
- `manifest.v2.chrome.json`
- `manifest.v2.development.json`

This would allow us to keep the explicit file names and have a cleaner file structure to represent version and mode specific overrides.

2023-01-08 15:06 UTC, mhluongo commented on webpack.config.ts
> +                }
Seconded.

2023-01-09 02:39 UTC, aurelsziebert commented on webpack.config.ts
> +                }
That would be simpler, I agree. Sometimes I tend to overcomplicate things.
Although the goal is reached on both way, and this is already a working solution, I'll take your advice, and make the change, because it makes the code cleaner, and safer. And it doesn't take much time anyway.
Thanks for the comment!

2023-01-09 04:09 UTC, aurelsziebert commented on manifest/manifest.chrome.json
> +  "minimum_chrome_version": "88",
Pushed, thanks for the comment.

2023-04-14 19:53 UTC, Shadowfiend commented
Manifest v3 isn't a primary concern right now, so we're going to hold off on additional work and close these PRs unless/until it bubbles back up.

2023-04-14 19:53 UTC, closed without merging