Custom RPCs - Request user confirmation before adding a custom network
tahowallet/extension pull request #2996
Opened 2023-02-07 07:38 UTC by hyphenized

Closes #2957 

Implements a popup to prompt the user for confirmation before adding a new network and changes `wallet_switchEthereumChain` and `wallet_addEthereumChain` to only work with connected dApps.

![image](https://user-images.githubusercontent.com/28708889/217181344-15a2165e-4d14-4600-bcb7-239f934cc936.png)

Pending tasks:
- Add network icons with fallbacks (chainlist & additional color coded / name only)
- Handle adding networks with the same chain as builtin networks
- Handle duplicate requests
- Handle requests for networks with the same chain Id as already stored networks

## Testing Env

```
SUPPORT_CUSTOM_NETWORKS=true
SUPPORT_CUSTOM_RPCS=true
```

## To Test
- [ ] Head over to [chainlist.org](https://chainlist.org), add a few custom networks
- [ ] You should see a confirmation prompt for each network you try to add
- [ ] Clicking on reject or closing the window should cancel the request
- [ ] Clicking on add should save the new network to the wallet

2023-02-07 17:06 UTC, jagodarybacka reviewed
Didn't hav time to test it manually, initial thoughts:

2023-02-07 17:06 UTC, jagodarybacka commented on ui/pages/AddNewEVMChain.tsx
> +      <form action="#">
Do we need this `form`?

2023-02-08 06:04 UTC, hyphenized commented on provider-bridge/index.ts
> -        event.data.request.method === "eth_accounts"
This adds the favicon and site title to the params sent to the background script, since we're no longer treating `eth_accounts` (#2983) calls as an indicator that a user wants to connect to a dApp we don't need to pass these anymore

2023-02-08 06:06 UTC, hyphenized commented on ui/pages/AddNewEVMChain.tsx
> +      <form action="#">
We do but I think we also need to move the confirmation handler to the `onSubmit` so the semantic value this form element provides is not lost

2023-02-08 14:18 UTC, jagodarybacka commented on ui/pages/AddNewEVMChain.tsx
> +      <form action="#">
yeah I was wondering if we have no onSubmit then this element adds little value 😄

2023-02-08 15:00 UTC, 0xDaedalus requested changes
Lets go ahead and at the very least add tests for:
- New methods in the provider-bridge service
- Logic inside the new `wallet_addEthereumChain` block

2023-02-08 15:00 UTC, 0xDaedalus commented on background/services/internal-ethereum-provider/index.ts
> +export const validateAddEthereumChainParameter = ({
Good call moving the validation logic out of here.  We can probably go one step further and move the definition into provider-bridge as well

2023-02-08 15:05 UTC, jagodarybacka requested changes
Hmmm weird but styles are broken for me 🤔 The rest is working as expected

![image](https://user-images.githubusercontent.com/20949277/217567783-35bfa891-137e-447a-ac9f-17acd48b97c2.png)

2023-02-15 13:45 UTC, jagodarybacka reviewed
Is this ready for another review? I see the styles are still broken 😛

2023-02-15 13:45 UTC, jagodarybacka commented on background/services/provider-bridge/tests/index.unit.test.ts
> +    it("should wait for user confirmation before calling wallet_AddEtherumChain", async () => {
```suggestion
    it("should wait for user confirmation before calling wallet_addEthereumChain", async () => {
```

2023-02-20 14:40 UTC, jagodarybacka reviewed
Looks good, small things left:

cc @VladUXUI should these buttons be fixed to the bottom of the screen? 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/20949277/220136285-c0aee1dd-6a98-4be2-9f6a-c8641f8a27fe.png">

2023-02-20 14:40 UTC, jagodarybacka commented on ui/pages/NewCustomNetworkRequest.tsx
> +          height: 50px;
These icons should have the same size: 
<img width="211" alt="image" src="https://user-images.githubusercontent.com/20949277/220135473-68a6e94a-f968-4c19-bccd-289eb160099b.png">

```suggestion
          width: 56px;
          height: 56px;
```

2023-02-20 16:24 UTC, VladUXUI commented
> Looks good, small things left:
> 
> cc @VladUXUI should these buttons be fixed to the bottom of the screen? <img alt="image" width="387" src="https://user-images.githubusercontent.com/20949277/220136285-c0aee1dd-6a98-4be2-9f6a-c8641f8a27fe.png">

Yeah, this is looking a bit off.
Background seems a bit darker, and buttons are not aligned with the rest of the UI
<img width="385" alt="image" src="https://user-images.githubusercontent.com/80846886/220158219-887c7832-107a-45fc-b283-c9709643f80e.png">

2023-02-23 00:13 UTC, 0xDaedalus approved these changes
Lets 🚢

2023-02-23 00:14 UTC, merged