Allow adding private key imported wallets in the service
tahowallet/extension pull request #3089
Opened 2023-02-27 18:39 UTC by jagodarybacka

Handle importing wallets with private key in the keyring service:
* save pk imported accounts in the encrypted vault
* handle serialization and deserialization of pk imported wallets
* handle siging messages with both keyrings and single wallets
* fix types and field names in the redux store

2023-03-09 15:04 UTC, Shadowfiend commented
> ⚠️ Please do not merge without code owner's approval! ⚠️

Btw this will be enforced by GitHub, as long as the target branch is `main`.

2023-03-09 19:21 UTC, Shadowfiend requested changes
Left some higher-level architectural thoughts on how to reconsider the addition of new methods and redux actions by instead adding new variants to the existing data structures, and reconsidering private keys as “simple” keyrings with only one key and no derivation capabilities.

2023-03-09 19:21 UTC, Shadowfiend commented on background/services/keyring/index.ts
> +export type SerializedWallet = {
Maybe let's put this in `persistence`? The de facto interaction style of the repo is that `index` is considered to be exporting types and data for consumption outside of the directory, so having this exported here means we expect to export access to the serialized wallet including private key. In practice, we don't currently intend to do that (unless we add private key exporting, but at that point the thing we expose here will likely already be encrypted, while this data type will carry unencrypted private keys).

Another option is just not to export the type, maybe—unclear if it's referenced elsewhere right now.

2023-03-10 11:14 UTC, jagodarybacka commented on background/services/keyring/encryption.ts
> +    cipherText: bufferToBase64(cipherText as Uint8Array),
my VSC typescript plugin was highlighting that, but no error in the console 🤔 may be a bug in VSC, will check

2023-03-14 16:39 UTC, jagodarybacka commented
- did some renames and other minor improvements (naming ideas still appreciated)
- created a single point of import both HD wallets and private keys
- right now I cannot see how merging HD keyrings and pk wallets into single array will be beneficial, both in the service and in the redux as they have different methods and properties. I need to merge it to the other PR to see how it will behave with selectors etc.

Moving this to draft for now, will notify when it is ready.

2023-04-20 16:06 UTC, Shadowfiend reviewed
Ok, so first as I've been digesting this, a categorical issue here on my end: we have mixed the concept of an HDKeyring, which is a keyring that has a mnemonic and can derive many addresses, with the general concept of a Taho keyring, which is here treated as where all internal accounts are managed. Conceptualized in the physical world, the Taho keyring service is a sort of keyring of keys AND keyrings once we finish this work.

My suggestion here is that we rename `KeyringService`, as well as the associated slice and the associated signer subcomponents, to be `InternalSignerService`, `internal-signer` slice, `SignerInternal` for the components, etc. The idea here is that the commonality among all of these isn't that they're keyrings anymore, it's that they are signers whose material we manage internally.

This would also entail renaming the types in `keyring/index.ts` that here are `Signer*` to `InternalSigner*`, which distinguishes them from the more generic types we're using for the signing slice and signing service.

It also should be fuel for us to distinguish between “this is a signing request for an internal signer”, which is a routing directive to go to the internal signer service, from the metadata used by the internal signer service to figure out if it needs a private key or a keyring to do the work (e.g. https://github.com/tahowallet/extension/blob/7784ccce5e9cd3ae9547c17e1ab3542793abc0ba/background/services/signing/index.ts#L141-L149 indicates the signing service knows something it really doesn't need to—it really just needs to know this is an internal account). This is also a generic top-level decision maker for whether we need to check for the keyring being locked/unlocked, etc.

I realize this is a pretty big suggestion/request, so posting it so we can ponder it a little while I do other parts of the code review.

2023-04-20 21:06 UTC, Shadowfiend reviewed
Couple more questions, still loading heh ⌛

2023-04-20 21:06 UTC, Shadowfiend commented on ui/pages/Onboarding/Tabbed/ImportPrivateKeyJSON.tsx
> +    }
This is feeling like debt piling on some debt decisions we made back in the day in terms of how we handle error flow.

I don't think it's blocking at all, but my suggestion for both keyring and private key (and JSON) import is to await an async thunk that returns success/failure, and handle that directly here, vs the current approach of managing this weird `importing` field that has `false`, `"pending"`, and `"done"` as values, and triggering effects based on them. The state update loop ends up being quite hard to follow and even harder to debug vs saying `await dispatch(import)` followed by `if (success) { ... } else { ... }`.

2023-04-20 21:06 UTC, Shadowfiend commented on ui/pages/Onboarding/Tabbed/ImportPrivateKeyJSON.tsx
> +      dispatch(sendEvent(OneTimeAnalyticsEvent.ONBOARDING_FINISHED))
Not blocking: is there a centralized place we could do this? e.g. as an effect on https://github.com/tahowallet/extension/blob/fa1552e74351ebb865ff70568e3832e1a27f8e3a/ui/pages/Onboarding/Tabbed/Done.tsx#L74 or similar?

2023-04-21 13:53 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +type SignerWithType = SignerPrivateKey | SignerHDKeyring
The `SigerRaw...` types are needed before we create the actual signer entity that is either `HDKeyring` or ether's `Wallet` types. So `SigerRaw...`s are holding metadata needed to create signers objects.

If you prefer other names we can go with something else instead of using `Raw`. Maybe `Metadata`?

2023-04-21 13:56 UTC, jagodarybacka commented on ui/pages/Onboarding/Tabbed/ImportPrivateKeyJSON.tsx
> +      dispatch(sendEvent(OneTimeAnalyticsEvent.ONBOARDING_FINISHED))
I believe we want to exclude onboarding with read only addresses. Other than that yeah we can refactor it later.

2023-04-26 09:54 UTC, jagodarybacka commented on ui/pages/Onboarding/Tabbed/ImportPrivateKeyJSON.tsx
> +    }
Done in https://github.com/tahowallet/extension/pull/3309

2023-04-26 11:42 UTC, hyphenized requested changes
Implementation looks good so far! Gave a first pass and left a few comments, will follow up shortly.

2023-04-26 11:42 UTC, hyphenized commented on background/services/keyring/index.ts
> +  | SignerRawJSONPrivateKey
I think we've abstracted this too early, we don't need the type guards yet either as we're only using them in a single place, and can already discriminate by the `type` property before passing each `import...` function it's required data rather than passing again the same object.

What do you think about naming this `RawSignerWithType`? If we're keeping the type aliases I'd suggest following the same naming pattern as well i.e. `RawSignerPrivateKey`, `RawSignerHDKeyring`, and so on.

2023-04-27 00:34 UTC, 0xDaedalus commented on background/redux-slices/keyrings.ts
> +  privateKeys: PrivateKey[]
Small nit here that the type name makes it seem like we're storing Private Keys in redux state

2023-04-27 00:34 UTC, 0xDaedalus commented on background/redux-slices/keyrings.ts
>        // so we ignore an empty list if the keyrings are locked.
We should update the comment here

2023-04-27 00:34 UTC, 0xDaedalus commented on background/services/keyring/index.ts
> +    } catch (e) {
IS there any value in logging the error here?

2023-04-27 00:34 UTC, 0xDaedalus commented on background/services/keyring/index.ts
> +    } catch (e) {
Same as above

2023-04-27 11:39 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +type SignerWithType = SignerPrivateKey | SignerHDKeyring
Changed in https://github.com/tahowallet/extension/pull/3331

2023-04-27 12:07 UTC, jagodarybacka commented on background/redux-slices/selectors/accountsSelectors.ts
> +  }
https://github.com/tahowallet/extension/pull/3331/commits/d82d83aa895e8efb68e86512178273cb7a50b8f5

2023-04-27 12:08 UTC, jagodarybacka commented on background/redux-slices/accounts.ts
> +  PrivateKey = "privateKey",
https://github.com/tahowallet/extension/pull/3331/files#diff-41888dfa5421a9149c733a79b8c8b7f83ca5c79b12b4346025e14f19ab31cb0dR28

2023-04-27 12:19 UTC, jagodarybacka commented on ui/public/images/add_wallet/import_priv_key.svg
https://github.com/tahowallet/extension/pull/3331/commits/b67a8a91138b0bb3d61872dc6d3269c914f70d9b

2023-04-27 13:06 UTC, jagodarybacka commented on ui/pages/Onboarding/Tabbed/Routes.ts
> +  IMPORT_PRIVATE_KEY: "/onboarding/import-priv-key",
https://github.com/tahowallet/extension/pull/3331/commits/30e5fc869ad51b561e1ea8d63778d7140d5bc2b2

2023-04-27 13:08 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +  async #importKeyring(signerRaw: SignerRawHDKeyring): Promise<string | null> {
[Comments updated](https://github.com/tahowallet/extension/pull/3331/files#diff-a8aee172609c7e4b51c07f3ba53e2e0c24786f91a74f1b03d2cc8cbbe3881e09R418)

2023-04-27 13:21 UTC, jagodarybacka commented on background/services/chain/index.ts
> +    const source = await this.keyringService.getSignerSourceForAddress(
https://github.com/tahowallet/extension/pull/3331/commits/c33ce42f86c1feda2fb0e40aca0627a9718e5eef

2023-04-27 13:29 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +    let signed: string
`signedTx` is declared below but https://github.com/tahowallet/extension/pull/3331/commits/3e436e73a930e57a8954735b6832bd9842f18708

2023-04-27 13:40 UTC, jagodarybacka commented on background/redux-slices/keyrings.ts
> +  privateKeys: PrivateKey[]
Yeah but idk what is the better name as the feature that distinguishes these wallets is that they are imported with private keys 🥲

2023-04-27 13:47 UTC, jagodarybacka commented on background/redux-slices/keyrings.ts
>        // so we ignore an empty list if the keyrings are locked.
https://github.com/tahowallet/extension/pull/3331/commits/caa734e184df9aadbe0534787ad10ae1b80acfa6

2023-04-27 14:16 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +    } catch (e) {
Yeah logging them won't hurt https://github.com/tahowallet/extension/pull/3331/commits/72eb623fcc743e181f1ea1938398bef69387d771

2023-04-27 14:40 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +      throw new Error(`Keyring not found for address ${account}.`)
https://github.com/tahowallet/extension/pull/3331/commits/d9f750ee63ab76e3dc6e58934e96970a3160ec6b there is still some cleanup to do about what is being logged and what it just thrown as error, will do it later

2023-04-27 15:04 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +    // TODO: check if this wallet already exists
https://github.com/tahowallet/extension/pull/3331/commits/6357ca1757b98bc8c89b680b7c9a75d84df12203

2023-04-27 15:11 UTC, hyphenized reviewed
This is looking great! Gave another pass through the rest of the files, left mostly minor comments.

2023-04-28 08:45 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +    if (isRawPrivateKey(signerRaw)) {
https://github.com/tahowallet/extension/pull/3331/commits/c3778039808abc092a92c1138e75feeec9a5f0ea

2023-04-28 08:57 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +  | SignerRawJSONPrivateKey
> discriminate by the type property before passing each import... function it's required data rather than passing again the same object

If I understand correctly what you would like to do - it would require to use `as` or other type casting solutions to ensure each import method is getting correct metadata. So idk if this would be cleaner solution than just having separate types here

I renamed them in the other PR already, lmk later if that's better.

2023-04-28 09:16 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +export type SignerMetadata = {
https://github.com/tahowallet/extension/pull/3331/commits/2519ed33634a8b76855de2d963ac29c5757af477

2023-04-28 09:46 UTC, jagodarybacka commented on background/services/keyring/index.ts
https://github.com/tahowallet/extension/pull/3331/commits/d366873f3339a4d9c6c00b843262195b1b8bc054

2023-04-28 09:56 UTC, jagodarybacka commented on background/redux-slices/migrations/to-28.ts
> +import { PrivateKey } from "../../services/keyring"
https://github.com/tahowallet/extension/pull/3331/commits/3e1a3fefc5d8c3de133c392d40a27b6a7d6eeff8

2023-04-28 10:07 UTC, jagodarybacka commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +const accountTypes = [
https://github.com/tahowallet/extension/pull/3331/commits/a983330a8d07511e0f89af61dd040626ca5b7d11

2023-04-28 10:08 UTC, jagodarybacka commented on background/services/keyring/index.ts
>    path: string | null
https://github.com/tahowallet/extension/pull/3331/commits/bb8f58ecdf77ed3bfe3092c8d6e4e0e74f83695f

2023-04-28 10:11 UTC, hyphenized commented on background/services/keyring/index.ts
> +  | SignerRawJSONPrivateKey
Sorry, by discriminating by the `type` prop I meant that we can do the following, and remove the type guards:

```ts
	 if (signerMetadata.type === SignerSourceTypes.privateKey) {
      address = this.#importPrivateKey(signerMetadata)
    } else if (signerMetadata.type === SignerSourceTypes.jsonFile) {
      address = await this.#importJSON(signerMetadata)
    } else {
      address = this.#importKeyring(signerMetadata)
    }
```

But it looks that it has already been done in c3778039808abc092a92c1138e75feeec9a5f0ea.

Moving on to the import methods, there doesn't seem to be a need for each of these to require this same `type` property. For instance, `importPrivateKey` only needs to be aware of the private key as a parameter.

2023-04-28 10:15 UTC, jagodarybacka commented on ui/pages/Onboarding/Tabbed/ImportPrivateKey.tsx
> +type Props = {
Yeah, I think it is very unlikely that we will ever need to reuse component props types, let's discuss it later.

2023-04-28 10:33 UTC, jagodarybacka commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +}
https://github.com/tahowallet/extension/pull/3331/commits/825d6cea68fc2a179831fa35365e80982af47895

2023-05-02 14:18 UTC, hyphenized submitted a review, later dismissed

2023-05-05 09:46 UTC, hyphenized approved these changes

2023-06-16 19:42 UTC, Shadowfiend commented
Let's switch the copy “Private Key Import” on the onboarding screen to “Import private key” to match “Import recovery phrase”

2023-07-05 20:00 UTC, Shadowfiend submitted a review, later dismissed
All righty, we are good to go here. Waiting on one more round of thoughts from the auditors and then we're going to land this puppy with great fanfare.

2023-07-07 22:24 UTC, Shadowfiend approved these changes
It is time 🏆

2023-07-07 22:24 UTC, merged