Daylight requests
tahowallet/extension pull request #3095
Opened 2023-02-28 17:19 UTC by 0xDaedalus

Closes #3087 

### Testing
The following should be true in order for this PR to pass testing:

- [ ] The extension does NOT get abilities when it starts up.
- [ ] The extension does NOT get abilities every hour.
- [ ] The extension DOES get abilities when the extension window is opened.
- [ ] Getting abilities should happen at most once per hour.
- [ ] When importing a new account - that accounts abilities should be fetched on import
- [ ] When adding an address to an already imported account - that addresses abilities should be fetched when added.

2023-03-01 06:02 UTC, hyphenized requested changes
Nicely done! Left a couple of comments, aside from that, it's looking great.

2023-03-01 09:19 UTC, kkosiorowska requested changes
Looks really good! However, I did find a small thing. When I am trying to add a ledger account, requests are sent for all addresses before I select anyone.

https://user-images.githubusercontent.com/23117945/222096119-189d4911-8be9-41e3-9313-da0c33f72a85.mov

2023-03-01 13:45 UTC, 0xDaedalus commented on background/services/abilities/index.ts
> +  }
whoopsie - good catch here

2023-03-01 13:46 UTC, 0xDaedalus commented on background/main.ts
> +      this.abilitiesService.refreshAbilities()
Yup - I think this is fine for now tbh.

2023-03-01 13:57 UTC, 0xDaedalus commented
Most feedback addressed - won't have time to dig into the multiple ledger requests before the next release so have created a follow-up issue: https://github.com/tahowallet/extension/issues/3100

2023-03-02 09:32 UTC, kkosiorowska commented on background/services/abilities/index.ts
> +    if (lastFetchTime && Number(lastFetchTime) + HOUR < Date.now()) {
It seems that the `<` should be set in reverse. Which makes more sense.  If lastFetchTime + hour is greater than the current time we shouldn't fetch data. 

I'll prepare a fix for this.

https://user-images.githubusercontent.com/23117945/222387316-c3aea1ba-b4f5-4327-a646-79e7f9e3966f.mov

2023-03-02 09:48 UTC, kkosiorowska commented
It would be good to have another person look at it after revisions. @jagodarybacka please take a look if everything works as expected.

2023-03-02 10:24 UTC, jagodarybacka approved these changes
✅

2023-03-02 10:29 UTC, merged