Add  basic tests for abilities
tahowallet/extension pull request #3140
Opened 2023-03-10 12:06 UTC by kkosiorowska

This PR adds tests for AbilitiesService. PR tests the performance of refreshing abilities and adding them.

2023-03-10 16:08 UTC, hyphenized commented on setupJest.ts
> +Object.defineProperty(window, "localStorage", { value: localStorageMock })
We can remove this, our version of Jest already [comes with support for localStorage](https://github.com/jsdom/jsdom/blob/master/Changelog.md#11120)

2023-03-13 12:31 UTC, 0xDaedalus requested changes
Code looks good - just some description and meta-level stuff to fix here.

I only commented on one of the `it` blocks but I do think that there's a real strong case for structuring test names like `should X when Y` or `should X if Y`.  Particularly when there are conditions when opposite behavior can be expected (like emitting / not emitting, refreshing / not refreshing, etc..)

2023-03-13 12:31 UTC, 0xDaedalus commented on background/services/abilities/tests/index.intedration.test.ts
> +import sinon from "sinon"
Slight type on the filename here - it should be index.`integration`.test.ts

2023-03-13 12:31 UTC, 0xDaedalus commented on background/services/abilities/tests/index.intedration.test.ts
> +    it("should not refresh abilities", async () => {
Let's add the condition under which this test passes to the test description (as well as the one above)

2023-03-17 11:47 UTC, 0xDaedalus approved these changes

2023-03-17 11:47 UTC, merged