Assign random colors to Chains in portfolio view.
tahowallet/extension pull request #3204
Opened 2023-03-28 17:55 UTC by 0xDaedalus

Closes https://github.com/tahowallet/extension/issues/3193

Assignment is not quite random - but can be switched to truly random in the future if we deem this is _really_ something we want.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/94649004/228325619-ca11fc09-1c01-4a5d-9624-b5526f45e438.png">

### To Test
- Import a wallet with assets across many networks.
- Confirm that each network is assigned a different color.

Latest build: [extension-builds-3204](https://github.com/tahowallet/extension/suites/11946270834/artifacts/626232794) (as of Fri, 31 Mar 2023 14:28:45 GMT).

2023-03-28 17:57 UTC, hyphenized commented
Should colors be assigned randomly for all networks or only custom? cc @VladUXUI

2023-03-30 14:08 UTC, 0xDaedalus commented
I did it by modifying the redux store and the component state itself - but you are correct this feature will not see the light of day until we add asset prices on custom networks.

2023-03-31 09:47 UTC, jagodarybacka requested changes
Found a place where it throws an error:

2023-03-31 09:47 UTC, jagodarybacka commented on ui/components/Overview/NetworksChart.tsx
>                {NETWORK_BY_CHAIN_ID[chainID].name}({percent}%)
This line will throw an error as NETWORK_BY_CHAIN_ID includes only built-in networks - we won't know the name of custom network for the chart's legend

2023-03-31 15:40 UTC, merged