Token Discovery - Add untrusted assets visibility toggler to settings
tahowallet/extension pull request #3250
Opened 2023-04-04 16:50 UTC by hyphenized

Adds a toggler to show/hide untrusted assets to the settings page

Closes #3213 

## To Test
- [x] Set a few tokens as trusted
- [x] Go to the settings page and toggle "Hide untrusted assets"
- [x] Check that the wallet asset list does not display the rest of untrusted assets, these should be under hidden assets now
- [x] Verify that trusted assets that are dust do not display if hide dust is enabled
- [x] Assets marked as hidden/trusted should not display the unverified asset warning icon
- Interact with an unverified asset, mark it as trusted/untrusted
  - [x] Wallet should no longer display warning sign in the asset list
  - [x] Wallet should no longer display unverified asset status in the single asset page
  - [ ] Single asset page should display Hide asset / Show asset
  - [ ] Clicking on either of these options should change the asset trusted status
- For unverified assets: 
  - [ ] In the single asset page, clicking on an unverified asset should bring up the warning slide up panel
  - [ ] With `hide untrusted assets` toggled on, the dialog should display `Hide asset` and `Trust asset`
  - [ ] With `hide untrusted assets` toggled off, the dialog should display `Close` and `Trust asset`
- For tokenlist assets: 
	- [x] In the single asset page, you should be able to hide it and send it to the hidden assets list
	- [x] Clicking on "Show" should send a token-list asset back to the main asset list
- [ ] Discovered assets should display transaction source when available

## Testing Env

```
SUPPORT_ASSET_TRUST=true
```

Latest build: [extension-builds-3250](https://github.com/tahowallet/extension/suites/12855255665/artifacts/692999684) (as of Fri, 12 May 2023 12:17:34 GMT).

2023-04-05 07:18 UTC, kkosiorowska commented on background/redux-slices/ui.ts
> +    showUntrustedAssets: boolean
Shouldn't we do a migration if we are changing the state?

2023-04-13 09:28 UTC, hyphenized commented on background/redux-slices/ui.ts
> +    showUntrustedAssets: boolean
We don't need one because this settings object is guaranteed to exist and we're only checking truthiness for this property value, so `undefined` is fine.

2023-04-13 15:03 UTC, jagodarybacka commented on background/redux-slices/ui.ts
> +    showUntrustedAssets: boolean
As we were always doing migrations with changes like this I think it may be better to continue that habit, even if this is not dangerous to skip this one as this is a boolean, next time someone will skip adding an object which will be a problem 😜 Or we can decide to stop doing unnecessary migrations if everyone agrees with that

2023-04-15 02:24 UTC, Shadowfiend commented
Quick Q here: I'm puzzled as to how this interacts with the show/hide hidden assets collapsing in the asset list. Is a hidden asset different from an untrusted asset? How does the user find out the distinction? Or is this work meant to supersede that work?

2023-04-18 07:46 UTC, kkosiorowska reviewed
Currently, after separating hidden assets, the toggler is not doing anything. 

https://user-images.githubusercontent.com/23117945/232706215-39387617-6721-4be7-8306-49fc9b822378.mov

2023-04-18 16:37 UTC, hyphenized commented
> Quick Q here: I'm puzzled as to how this interacts with the show/hide hidden assets collapsing in the asset list. Is a hidden asset different from an untrusted asset? How does the user find out the distinction? Or is this work meant to supersede that work?

Hidden assets may be asset balances that are dust, assets that have not been marked as trusted or a combination of the former (assets market as trusted but which balances are considered dust). Does that makes sense? cc @VladUXUI

@kkosiorowska I've fixed the toggler, please give it another look when you can.

2023-04-19 11:40 UTC, kkosiorowska reviewed
It looks really good ⚡️Let's still wait for Vlad's response.

2023-04-19 11:40 UTC, kkosiorowska commented on background/redux-slices/selectors/accountsSelectors.ts
> -      } else if (isPresent) {
I would like to confirm if we want to start showing assets with 0$ balance under the "hidden" section? @VladUXUI 

<img width="250" alt="Screenshot 2023-04-19 at 13 08 51" src="https://user-images.githubusercontent.com/23117945/233056793-95e50930-0e69-4209-86c9-10b61ed75ce1.png">

2023-04-19 11:40 UTC, kkosiorowska commented on background/redux-slices/selectors/accountsSelectors.ts
> +      hideUntrustedAssets
Non-blocking comment

I wonder if it's better to make it one object with settings for assets and pass it here. What I mean is that I would like to avoid increasing the number of parameters for the function.

2023-04-19 11:40 UTC, kkosiorowska commented on background/redux-slices/selectors/accountsSelectors.ts
> +  }
🚀

2023-04-19 15:46 UTC, hyphenized commented on background/redux-slices/selectors/accountsSelectors.ts
> -      } else if (isPresent) {
This is actually a bug, these should appear as "< 0,01" since they are dust balances(not zero). I've added some logic to hide these for now in [`e956630` (#3250)](https://github.com/tahowallet/extension/pull/3250/commits/e956630fb2f7b1b71aa1c37e2bd82d7c00f731ac)

<img width="436" alt="image" src="https://user-images.githubusercontent.com/28708889/233129379-0caf1f07-ca6c-4ee5-9297-fd52ae82c2e5.png">

2023-04-19 15:47 UTC, hyphenized commented on background/redux-slices/selectors/accountsSelectors.ts
> +      hideUntrustedAssets
Agree, we don't need the to pass the current network as a parameter anymore either

2023-04-20 11:00 UTC, VladUXUI commented
Couple of things here on the UX side (although uncertain what to actually comment on)
1 - If i marked an asset as trusted, it shouldn't have the yellow Attention icon anymore
2 - Trust/untrust is missing from the token details page 
<img width="425" alt="image" src="https://user-images.githubusercontent.com/80846886/233346561-77d837a5-511b-4e16-833a-96d1bfd81d71.png">

2023-05-03 12:51 UTC, jagodarybacka requested changes
- [x] once I trust asset I can no longer untrust it, Hide asset is doing nothing
![image](https://user-images.githubusercontent.com/20949277/235920982-5ed4c44c-aa13-43de-a522-2627965bdaa4.png)

- [x] on single asset page I can see Asset not verified for tokens from token lists 
![image](https://user-images.githubusercontent.com/20949277/235921166-80ee2cad-e5d0-466e-acaa-a5b42b5af011.png)

2023-05-03 13:43 UTC, 0xDaedalus requested changes
I'd like to requests 2 e2e tests here, lets test the following

1. For a token that is initially trusted:
- Set token to untrusted
- Token displays as untrusted in Wallet
- Set it back to trusted
- Token displays as trusted in Wallet

2. For a token that is initially untrusted:
- Set token to trusted
- Token displays as trusted in Wallet
- Set it back to untrusted
- Token displays as untrusted in Wallet

2023-05-08 14:44 UTC, hyphenized commented
> * [ ]  once I trust asset I can no longer untrust it, Hide asset is doing nothing
>   ![image](https://user-images.githubusercontent.com/20949277/235920982-5ed4c44c-aa13-43de-a522-2627965bdaa4.png)

Thanks for the review, fixed!
> * [ ]  on single asset page I can see Asset not verified for tokens from token lists
>   ![image](https://user-images.githubusercontent.com/20949277/235921166-80ee2cad-e5d0-466e-acaa-a5b42b5af011.png)

Not sure if this is the correct behaviour, could you confirm @VladUXUI ?

2023-05-08 14:46 UTC, Shadowfiend commented
> on single asset page I can see Asset not verified for tokens from token lists
> Not sure if this is the correct behaviour

As I absorb this feature into my brain—why would we see Asset not verified for a token list asset? We have baseline trust for token list assets, right? And Asset not verified is a textual reminder that an asset is not trusted, correct?

2023-05-09 08:06 UTC, VladUXUI commented
Token list assets should't have any verified or unverified behaviour/status. As these are already verified and trusted by us

2023-05-10 11:05 UTC, jagodarybacka requested changes
Some ideas and improvements

2023-05-10 11:05 UTC, jagodarybacka commented on ui/components/Wallet/AssetWarningSlideUp.tsx
> +            <div className="right">
Can we use `SharedAddress` component here?

2023-05-10 11:05 UTC, jagodarybacka commented on ui/pages/SingleAsset.tsx
> +function TrustToggler({
`TrustToggler` deserves to be in its own file I think 😉

2023-05-11 13:07 UTC, hyphenized commented on background/redux-slices/tests/accounts.unit.test.ts
> +              createSmartContractAsset({ metadata: {} }),
No metadata means no token lists so this is an unverified, untrusted asset

2023-05-11 13:08 UTC, hyphenized commented on ui/components/Wallet/AssetWarningSlideUp.tsx
> +            <div className="right">
We could but `SharedAddress` has some logic specific to name resolution.

2023-05-24 08:17 UTC, kkosiorowska commented
There has been a change in logic for trusted/untrusted assets. The current status of this feature can be found in https://github.com/tahowallet/extension/pull/3394. Let's close it.

2023-05-24 08:17 UTC, closed without merging