Custom Token Import - Allow manually importing assets
tahowallet/extension pull request #3261
Opened 2023-04-06 22:24 UTC by hyphenized

Allows manually adding tokens from the asset list and the settings page

<img width="376" alt="image" src="https://user-images.githubusercontent.com/28708889/230504565-84da24e1-25b6-4590-99ae-ee0a9af0f996.png">

## Testing Env

```
SUPPORT_CUSTOM_NETWORKS=true
SUPPORT_CUSTOM_RPCS=true
```

## To test
- [ ] Add a custom network
- [ ] Scroll down the asset list, click on add custom asset
- [ ] Input a erc20 token address, check that balance and symbol appear
- [ ] Attempt to "add asset", check that a toast displays and the asset now appears in the asset list after a balance refresh
- [ ] Input the same erc20 token address, verify a warning shows up with "asset already added"
- [ ] Input an account address or an invalid address, you should see an error "invalid contract address"

2023-04-07 08:34 UTC, VladUXUI commented
Upon testing i realised we need a more prominent way to show what network you are adding the token to.

2023-04-07 09:54 UTC, kkosiorowska reviewed
I took a quick look. Some minor thoughts.

2023-04-07 09:54 UTC, kkosiorowska commented on background/lib/logger.ts
> +
Should we always use this function now?

2023-04-07 09:54 UTC, kkosiorowska commented on background/main.ts
> +          sameEVMAddress(contractAddress, asset.contractAddress)
Non-blocking comment
I have a feeling that maybe we could create a separate function for this condition. Something like `isMatchingFungibleAsset`.

2023-04-07 09:54 UTC, kkosiorowska commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +              customStyles={{ "--tooltip-icon-color": "var(--green-20)" }}
Non-blocking comment
It is for the tooltip component. Maybe it is simpler to add a color option in the props in that case?

2023-04-07 09:54 UTC, kkosiorowska commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +                    </a>
Why not use SharedLink?

2023-04-07 09:54 UTC, kkosiorowska commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +                <strong>{assetData?.balance ?? "Balance"}</strong>
Do we not want to translate `Balance` and `Name`?

2023-04-07 13:51 UTC, 0xDaedalus requested changes

2023-04-07 13:51 UTC, 0xDaedalus commented on background/main.ts
> +  async queryCustomTokenDetails(
This feels like it should be a method in `chainService` - I know we unfortunately already have some complicated methods in `main.ts` but in general I think we've moved away from putting application logic in this file and have mostly been using it as a connector between the ui thread & background thread (either through event listeners & emitters or direct method calls via background async thunks).

2023-04-07 13:51 UTC, 0xDaedalus commented on ui/_locales/en/messages.json
> +      "footer.hint": "How to add a custom asset?"
This should probably either be

`How to add a custom asset`
or
`How do I add a custom asset?` if we want to keep the `?`

cc @VladUXUI

2023-04-07 13:51 UTC, 0xDaedalus commented on ui/_locales/en/messages.json
> +      "addCustomAssetAction": "add custom asset"
```suggestion
      "addCustomAssetAction": "Add custom asset"
```

2023-04-07 13:51 UTC, 0xDaedalus commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +    </svg>
Rather than defining this inline - lets place a `.svg` file in the `ui/public/images` folder and then import it here.

2023-04-07 13:51 UTC, 0xDaedalus commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +    )) as unknown as AssetData
As a rule I think we should avoid this kind of casting - especially since we know that `checkTokenContractDetails` can return `null` in some cases.  Even though we handle this case a few lines by showing an error if `details === null` we don't want our typings to diverge from what is actually going on.

2023-04-10 09:08 UTC, jagodarybacka commented on background/lib/logger.ts
> +
I don't think so, we should carefully pick errors that are meaningful for debugging before we put them into logs

2023-04-10 09:29 UTC, hyphenized commented on background/lib/logger.ts
> +
If it helps reduce repetition. Something to note is that this only works well for string errors and, on the frontend side an uncaught error will also be logged by the error boundary at `ErrorFallback`.

2023-04-10 09:30 UTC, hyphenized commented on background/main.ts
> +          sameEVMAddress(contractAddress, asset.contractAddress)
We could but we're comparing a contract address against an asset, which is a good fit for sticking to `sameEVMAddress` here I think.

2023-04-10 09:34 UTC, hyphenized commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +              customStyles={{ "--tooltip-icon-color": "var(--green-20)" }}
Yes it would be simpler, but the goal is to allow customizing more than just the tooltip icon color by overriding css variables. In that scenario, it wouldn't be very practical to have one property per style override.

2023-04-10 09:34 UTC, hyphenized commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +                <strong>{assetData?.balance ?? "Balance"}</strong>
Whoops 🤦  good catch!

2023-04-10 09:37 UTC, hyphenized commented on background/main.ts
> +  async queryCustomTokenDetails(
I've moved most of the logic to the chain service, which should make this easier to test as well.

2023-04-10 09:38 UTC, hyphenized commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +    )) as unknown as AssetData
I agree, however I consider this is an exception given the type definition for `AssetData` is the "correct" thunk return type.

2023-04-10 09:39 UTC, jagodarybacka commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +  type AssetData = AsyncThunkFulfillmentType<typeof checkTokenContractDetails>
does this type need to be inside the component? most often types are defined above the react components using them

2023-04-10 09:39 UTC, jagodarybacka commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +    )) as unknown as AssetData
If i remember correctly dispatch is not returning correct types so the best we can do is just be careful and make the casts here the same as in the background actions 🤔

2023-04-10 09:39 UTC, jagodarybacka commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +  const [{ loading, error, assetData }, setState] = useSetState<{
Isn't it achieving the same outcome as the `useReducer`?

2023-04-11 16:55 UTC, merged