Block the signing button when a limit is changing
tahowallet/extension pull request #3283
Opened 2023-04-19 09:04 UTC by kkosiorowska

Closes #3135 

This PR makes sure that the user sets the correct limit. The problem is that the user has the option to sign the transaction without approving the limit. It may appear to him that he has changed the limit, however, the limit will be set correctly when he clicks the confirm button. The changes ensure that the limit is set correctly.

### UI

### To Test
- [ ] check if the sign button is disabled when the user is updating the limit field (check for ledger account also)

2023-04-20 09:13 UTC, jagodarybacka commented
I'll review 👀

2023-04-20 10:20 UTC, jagodarybacka requested changes
Works fine, checked other types of transactions too and they are all ok. 

I wonder if we can somehow avoid using context here, as this is adding another layer of state management. But on the other hand, this button locking mechanism is purely on the frontend side so I'm ok leaving it here. Let's improve naming and we are good to go I think.

2023-04-20 10:20 UTC, jagodarybacka commented on ui/utils/signing.ts
> +  toggle: (value: boolean) => void
I would specify what is this toggling in the function name

2023-04-20 15:31 UTC, Shadowfiend commented
I suggest we use redux state instead of a context here. We can make it fairly generic to support any situation where an edit action is happening in the signing flow, e.g. an `additionalSigningStatus` redux field that can be set to `"editing" | undefined`.

A slightly bigger issue IMO: the current approach doesn't really tell the user why the sign button is disabled—say they start editing, update, and forget to hit save. Then they see they can't sign. How do they know that all they have to do is click save?

2023-04-21 10:45 UTC, kkosiorowska commented
> I suggest we use redux state instead of a context here. We can make it fairly generic to support any situation where an edit action is happening in the signing flow, e.g. an `additionalSigningStatus` redux field that can be set to `"editing" | undefined`.

Let's do it this way.

> A slightly bigger issue IMO: the current approach doesn't really tell the user why the sign button is disabled—say they start editing, update, and forget to hit save. Then they see they can't sign. How do they know that all they have to do is click save?

@VladUXUI Do you have any suggestions to solve this problem?

2023-04-21 11:10 UTC, VladUXUI commented
Of the top of my head, we should add “you have unsaved changed” either as a notification or as a tooltip on hover over disabled button.
or just autosave the amount after 3/4 seconds of pause in writing 

I would go with tooltip tbh, it has the least amount of questions and unknowns

2023-04-24 14:01 UTC, jagodarybacka approved these changes
Works fine

2023-04-24 14:01 UTC, jagodarybacka commented on ui/components/Signing/Signer/TransactionButton.tsx
> +  const renderButton = () => (
Idk if we are getting much cleaner code making it a function

2023-04-24 14:05 UTC, merged