Add support for wallet_watchAsset
tahowallet/extension pull request #3285
Opened 2023-04-19 14:59 UTC by 0xDaedalus

This support adds support for [`wallet_watchAsset`](https://eips.ethereum.org/EIPS/eip-747) which can allow users to easily add tokens via dapps.

### To Test
- [ ] Add Fantom network to the wallet
- [ ] Navigate to https://spooky.fi/#/swap
- [ ] Connect to the dapp
- [ ] In the asset lists dropdown - click on the`+` sign next to an asset that you have a balance for but is not displayed in the wallet (currently BOO and 1ART should work)
- [ ] Open the wallet and see the tokens show up under the `Hidden Assets` section.

2023-04-19 15:38 UTC, hyphenized requested changes
Looks good, left some comments

2023-04-19 15:38 UTC, hyphenized commented on background/services/internal-ethereum-provider/index.ts
> +            return false
Shouldn't we throw instead of returning `false`?

2023-04-19 15:38 UTC, hyphenized commented on background/services/internal-ethereum-provider/index.ts
> +          contractAddress: options.address,
Let's normalize these contract addresses before saving them

2023-04-20 10:06 UTC, kkosiorowska approved these changes
LGTM ✅

2023-04-20 10:07 UTC, merged