Custom Networks - Add delete network confirmation modal
tahowallet/extension pull request #3302
Opened 2023-04-21 14:54 UTC by hyphenized

## To Test

- [ ] Attempt to remove a custom network
- [ ] Closing or cancelling the modal should not delete the network
- [ ] After confirming the network should be removed from the wallet

2023-04-24 07:02 UTC, kkosiorowska commented
I'll review 👀

2023-04-24 07:31 UTC, kkosiorowska requested changes
Looks really good ⚡️Some comments:

- [x] When the network name is long the text jumps to the next line. It doesn't look good in my opinion. Maybe we could improve it somehow?
- [x] Also when the text jumps to the next lines the buttons are truncated.

![Screenshot 2023-04-24 at 09 22 00](https://user-images.githubusercontent.com/23117945/233927592-c7d68f4a-0817-45bc-9568-36571e4013b6.png)

I have noticed one more thing. It is not within the scope of this PR. I have added the EVMOS network. After removing the network, I see that in the portfolio I still have a preview of the EVMOS token. Shouldn't it disappear when the network is removed?

https://user-images.githubusercontent.com/23117945/233927986-094fa936-0ef7-4b0c-8a7b-b7a88ca6ea54.mov

2023-04-24 07:31 UTC, kkosiorowska commented on ui/pages/Settings/SettingsCustomNetworks.tsx
> +      setNetworkToDelete(null)
Non-blocking comment
It could be packaged into a separate cleaning function.

2023-04-24 20:25 UTC, Shadowfiend reviewed
Need to do a quick test drive but this looks good. 

I had trouble bringing up the add custom RPC page but that's unrelated to this change, will pursue separately.

2023-04-25 12:13 UTC, kkosiorowska commented
@Shadowfiend is OOO. Let's not block the main tests.

2023-04-25 12:17 UTC, merged