Make custom tokens visible in the asset list even if they have a balance of zero
tahowallet/extension pull request #3313
Opened 2023-04-26 12:24 UTC by kkosiorowska

2023-05-03 09:53 UTC, jagodarybacka requested changes
Some improvements ⬇️ 

Also - on other networks trusted and untrusted assets switched sections:

https://user-images.githubusercontent.com/20949277/235885224-7d7fb89c-31e9-46b9-a572-823f882765c2.mov

2023-05-03 09:53 UTC, jagodarybacka commented on background/redux-slices/utils/asset-utils.ts
> +export function isCustomAsset(asset: AnyAsset | undefined): boolean {
I would assume the asset will be always present when passed to this function - expecting undefined may be more convenient but may also hide some bugs
```suggestion
export function isCustomAsset(asset: AnyAsset): boolean {
```

2023-05-03 09:53 UTC, jagodarybacka commented on background/redux-slices/selectors/accountsSelectors.ts
> +      } else if (!isCustom ? isPresent : true) {
```suggestion
      } else if (isCustom || isPresent) {
```

2023-05-03 09:53 UTC, jagodarybacka commented on background/redux-slices/accounts.ts
> +            ) {
```suggestion
            if (
              isCustomAsset(asset) ||
              isBuiltInNetworkBaseAsset(asset, network)
            ) {
```

2023-05-03 09:53 UTC, jagodarybacka commented on background/redux-slices/accounts.ts
> +            if (
Can we combine these two ifs?

2023-05-08 08:35 UTC, kkosiorowska commented on background/redux-slices/accounts.ts
> +            ) {
It isn't what we expect. Take a look at the photo below. 
**Correct condition**
If the balance is zero and it isn't a custom asset and it isn't a base network asset we shouldn't add it to balances (go to return).

<img width="250" alt="Screenshot 2023-05-08 at 10 14 19" src="https://user-images.githubusercontent.com/23117945/236776274-cf14036d-d692-4f55-9e1c-eff95491a145.png">

2023-05-08 09:50 UTC, kkosiorowska commented
Let's wait with this PR until we merge this [one](https://github.com/tahowallet/extension/pull/3250).

2023-05-08 10:00 UTC, hyphenized commented
> Let's wait with this PR until we merge this [one](https://github.com/tahowallet/extension/pull/3250).

Good catch! The conditionals for token visibility have already been refactored there but we can also cherry pick some of that work here if we need to push this out faster

2023-05-08 14:18 UTC, 0xDaedalus commented
Lets add a couple of unit tests here as well - we should just need two:  One for `computeCombinedAssetAmountsData` and one for `updateAccountBalance`

2023-06-06 11:12 UTC, jagodarybacka commented
@kkosiorowska Is this PR still valid and we should merge it at some point or not?

2023-06-06 11:23 UTC, kkosiorowska commented
> @kkosiorowska Is this PR still valid and we should merge it at some point or not?

@jagodarybacka PR was blocked by Verified/Unverified tokens. It needs to be updated and tested again. I should be looking into it this week.

2023-06-14 11:32 UTC, kkosiorowska commented
> I don't think this is a good idea fwiw. If i sell my asset, how do i hide the dust from it?

We are able to force a newly added asset to be displayed (when the balance is 0). In the case where we sell an asset and its balance is close to zero we are able to hide this.

2023-06-15 01:12 UTC, Shadowfiend commented
> > I don't think this is a good idea fwiw. If i sell my asset, how do i hide the dust from it?
> 
> We are able to force a newly added asset to be displayed (when the balance is 0). In the case where we sell an asset and its balance is close to zero we are able to hide it.

I think if we've implemented, in the custom token add page, the message that the asset will be added but hidden due to having 0 balance + hide dust being enabled, then we should avoid getting to this level of contortion in the code, because it's going to have the potential to get real nasty. e.g. when do we consider an asset to be ”new“ and subject to this? Do we have to wait for balance to go over 0 and then drop back under it? Are we instead saying the asset is visible at exactly 0 but not at fractionally over 0? Etc.

2023-06-16 04:42 UTC, hyphenized commented on background/redux-slices/accounts.ts
> +              isUntrustedAsset(asset) ||
If the asset already exists it will likely be part of a token list assets and not a custom asset, in that case this won't trigger right?

2023-06-16 07:46 UTC, kkosiorowska commented
> EDIT to say: if it's not clear, I'm basically for killing this PR completely, BUT I think it's ultimately a call for Vlad/Haley to make 😁

It seems to me that Vlad has noticed an important issue.  I don't think this PR adds much value for the user. I'm okay with closing it.

@VladUXUI  Please let us know what you think.

2023-06-16 08:07 UTC, VladUXUI commented
Yeah, let's close. I think this will add more confusion to user and not enough value. Seeing 0 token assets isn't useful for many people. Also as a user i will rarely add a 0 balance asset just for the fun of it

2023-06-16 08:13 UTC, closed without merging