Plumbing - Cleanup old onboarding files
tahowallet/extension pull request #3314
Opened 2023-04-26 17:00 UTC by hyphenized

Closes #3311

## To Test
- [ ] Check onboarding still works as usual
- [ ] Removing all accounts should open up the onboarding tab
- [ ] Onboarding tab should open post install

2023-05-02 13:48 UTC, jagodarybacka requested changes
Minor fixes requested ⬇️ 

Also I would vote to make it a separate release as this is -2k lines and I'm afraid of how it will affect review time

2023-05-02 13:48 UTC, jagodarybacka commented on ui/index.ts
> +        url: browser.runtime.getURL("tab.html#onboarding"),
```suggestion
        url: browser.runtime.getURL(ONBOARDING_ROOT),
```

2023-05-02 13:48 UTC, jagodarybacka commented on ui/pages/Tab.tsx
> -    : BrowserTabContainer.Legacy
We can remove Legacy version from `BrowserTabContainer` component

2023-05-02 13:48 UTC, jagodarybacka commented on ui/index.ts
> +        url: browser.runtime.getURL("tab.html#onboarding"),
also here: https://github.com/tahowallet/extension/blob/onboarding-cleanup/src/background.ts#L10

2023-05-02 13:48 UTC, jagodarybacka commented on ui/index.ts
> +        url: browser.runtime.getURL("tab.html#onboarding"),
we can remove flag: https://github.com/tahowallet/extension/blob/onboarding-cleanup/.env.defaults#L21

2023-05-04 08:08 UTC, kkosiorowska reviewed
I think it's also a good idea to find and next close the issues for old onboarding. One of them:

https://github.com/tahowallet/extension/issues/2630

2023-05-25 12:08 UTC, kkosiorowska commented on ui/index.ts
> +        url: browser.runtime.getURL("tab.html#onboarding"),
Fixed.

2023-05-25 12:27 UTC, kkosiorowska approved these changes
LGTM :white_check_mark:

2023-05-25 12:28 UTC, merged