RFB 4: One-Off Keyring Design
tahowallet/extension pull request #3372
Opened 2023-05-09 22:17 UTC by Shadowfiend

Retrospective RFB for the base work in #3089 (the internal signer service and the hd-keyring work that underpinned exports there).

2023-05-10 12:24 UTC, jagodarybacka requested changes
Looks good. Only typo in BIP number is blocking

2023-05-11 19:31 UTC, Shadowfiend commented on rfb/rfb-4-one-off-keyring-design.adoc
> +direct export of the underlying mnemonic for HDKeyrings.
I think I'm going to flip this and refer to `HDKeyring` instead of HD wallet everywhere.

2023-05-11 19:33 UTC, Shadowfiend commented on rfb/rfb-4-one-off-keyring-design.adoc
> +Private keys and keyrings can both be imported. In the event that a private key
I think yes, in that mnemonics only produce keyrings, and only keyrings can produce mnemonics. It just depends whether you want to look at it from the perspective of the input (mnemonic) or output (keyring). I'm going to leave this unchanged for now, but open to a distinction I haven't thought of.

2023-05-11 19:33 UTC, Shadowfiend commented on rfb/rfb-4-one-off-keyring-design.adoc
> +private key to make provenance clear.
I'll update this since I expect we'll land 3377 before folks start poking at the code.

2023-05-11 19:51 UTC, Shadowfiend commented
Going to hold as draft until we land #3377, otherwise this is ready to go.

2023-05-12 10:50 UTC, jagodarybacka approved these changes
All good ✅

2023-05-12 15:39 UTC, merged