New approach to daylight feature
tahowallet/extension pull request #3375
Opened 2023-05-10 09:16 UTC by kkosiorowska

2023-05-11 12:10 UTC, jagodarybacka requested changes
Some improvements, haven't tested manually yet ☺️

2023-05-11 12:10 UTC, jagodarybacka commented on background/services/abilities/index.ts
> +          if (JSON.stringify(ability) !== JSON.stringify(existingAbility)) {
Are we sure that `ability` and `existingAbility` objects have the same structure - same order of fields etc?

2023-05-11 12:10 UTC, jagodarybacka commented on background/services/abilities/index.ts
> +              ability.completed === true && completed === false
Why we compare booleans like this?
```suggestion
            const updateCompleted = ability.completed && !completed
```

2023-05-11 13:13 UTC, kkosiorowska commented on background/services/abilities/index.ts
> +     * There is an exception when the ability is really completed we want to update this property as well.
> What does `really completed ability` mean?

Let's make it clearer. I mean that the ability was marked as completed in the Daylight API.

2023-05-12 06:49 UTC, kkosiorowska commented on background/services/abilities/tests/index.integration.test.ts
> +        normalizeDaylightAbilities(daylightAbilities, address)
This is exactly what we want. The ability has been removed from the API but it is stored in the cache all the time. Therefore, in the next step, we change the property value of this element `removedFromUi=true`. Editing `daylightAbilities` allows you to see the changes that have occurred in the API. But let me check if we can improve this to be more clear.

2023-05-12 21:03 UTC, Shadowfiend requested changes
Left a couple of specific changes and one bigger suggestion on a different way to structure the sync. Let me know what you think!

2023-05-12 21:03 UTC, Shadowfiend commented on background/services/abilities/index.ts
> +    await this.updateAbilities(normalizedAbilities)
Boy howdy, I forgot how annoying syncing is.

I'd like to suggest a somewhat simplified approach here that goes through a single method and then a db update:

```typescript
  /**
   * Syncs a set of new abilities against the ones being tracked in the cache.
   * Adds new abilities, marks existing ones as completed if the new entry
   * indicates they've been completed, and marks any abilities that are not in
   * the new set as removed from the UI.
   *
   * @return The latest sorted abilities list.
   */
  async syncAbilities(latestAbilities: Ability[]): Promise<Ability[]> {
    const cachedAbilities = await this.db.getAbilities()
    const cachedAbilitiesById = Object.fromEntries(
      cachedAbilities.map((ability) => [ability.abilityId, ability])
    )

    const syncedAbilities = latestAbilities.map((latestAbility) => {
      const cachedAbility = cachedAbilitiesById[latestAbility.abilityId]
      // Delete the cached entry so we can use the final set of ids in
      // cachedAbilitiesById as a proxy for ids that were not seen in the
      // latest abilities.
      delete cachedAbilitiesById[latestAbility.abilityId]

      const cachedCompleted = cachedAbility?.completed ?? false

      return {
        ...latestAbility,
        removedFromUi: cachedAbility?.removedFromUi ?? false,
        completed: cachedCompleted || latestAbility.completed,
      }
    })

    await this.db.updateAbilities([
      ...syncedAbilities,
      // Remaining abilities here are the ones that were not seen from
      // Daylight, mark them as removed from the UI.
      ...Object.values(cachedAbilitiesById).map((ability) => ({
        ...ability,
        removedFromUi: true,
      })),
    ])

    return this.db.getSortedAbilities()
  }

  async pollForAbilities(address: NormalizedEVMAddress): Promise<void> {
    const latestDaylightAbilities = await getDaylightAbilities(address)
    const latestAbilities = normalizeDaylightAbilities(
      latestDaylightAbilities,
      address
    )

    const updatedAbilities = await this.syncAbilities(latestAbilities)

    this.emitter.emit("updatedAbilities", {
      address,
      abilities: updatedAbilities,
    })
  }
```

I believe this makes all of the updates in one pass, avoids `reduce`[^1], and makes the overall flow of the code clearer. One thing it does *not* do is filter out abilities that haven't changed from the `bulkPut`. Even though we can try to skip `bulkPut`ing abilities that had no changes, I don't think we gain a lot vs the added complexity. I believe we're really talking about filtering out on the order of 10/20/30 records by doing this, and I don't think the puts are expensive enough on these to justify the extra work we're doing with JSON serialization and key sorting[^2].

Note that this assumes we *do* want to keep items in the db if they disappear from Daylight. If we don't, we can adjust it a bit to do a `bulkDelete`.

Thoughts?

[^1]: A general rule for me is that `reduce` should be a last resort, because it can be quite difficult to follow how it produces its final outcome. Even though it can be slower on paper to handle the same array more than once or `put` a larger array instead of a smaller one, the size of arrays we're dealing with here are small enough that it shouldn't be a primary concern.

[^2]: Not really relevant with this change, but I think it would be cheaper overall to implement a simplified [`deepEqual`](https://www.npmjs.com/package/deep-equal)-type check than to sort + serialize.

2023-05-15 09:33 UTC, kkosiorowska commented on background/services/abilities/index.ts
> +    await this.updateAbilities(normalizedAbilities)
Thanks for your awesome thoughts. Let's apply it to make it better. 🚀

> Note that this assumes we do want to keep items in the db if they disappear from Daylight. If we don't, we can adjust it a bit to do a bulkDelete.

I think we can give it up and just remove it from db. Since the user can mark an ability as removed himself, we wanted to let the user know that the ability has been removed. However, this doesn't really add much value to the user. So let's just remove those abilities.

2023-05-15 09:38 UTC, kkosiorowska commented on background/services/abilities/index.ts
> +      removedFromUi: true,
The goal was to show that the ability was removed so that the user could notice it. But this doesn't really add much value to the user  So let's just remove those abilities.

2023-05-15 10:57 UTC, Shadowfiend commented on background/services/abilities/db.ts
> +       * Boolean can't be indexed. Let's remove the unnecessary indexes.
The dexie docs make me think we might have needed to pass something extra to the function to avoid that. That said, I'm fine without an auto-incrementing value here right now tbh.

2023-05-15 13:19 UTC, kkosiorowska commented on background/services/abilities/db.ts
> +    return this.abilities.orderBy("magicOrderIndex").toArray()
We also show the abilities removed by the user. This function should return all the abilities sorted by `interestRank`. This is to take advantage of sorting through the db rather than the UI.

2023-05-15 14:11 UTC, kkosiorowska commented on background/main.ts
>      })
Yes I agree. At the time of [implementation](https://github.com/tahowallet/extension/pull/2981#discussion_r1097298305), it seemed to me the least invasive solution.  Let's create a separate ticket for that https://github.com/tahowallet/extension/issues/3384.

2023-05-15 17:51 UTC, Shadowfiend requested changes
Left a few more requests, going to try to test drive this today so we can be ready to land it tomorrow—or I might decide to merge as-is and we can handle additional changes in a follow-up, will see when I get to the testing part.

2023-05-15 17:51 UTC, Shadowfiend commented on background/services/abilities/index.ts
> +        ])
Since this logic is transforming the wallet concept of abilities to the db's index model, what do you think about pushing that responsibility to the db? In practice this would mean making `removeAbilities` take an `Ability[]`, and doing this conversion to the index representation internally.

2023-05-16 08:02 UTC, kkosiorowska commented on background/services/abilities/index.ts
> +      accountsToTrack.map((account) => normalizeEVMAddress(account.address))
I think it makes a lot of sense. This would save further calls to the `normalizeEVMAddress` method.

2023-05-16 10:47 UTC, Shadowfiend commented on background/services/abilities/tests/index.integration.test.ts
> +type AbilitiesServiceExternalized = Omit<AbilitiesService, ""> & {
Got it. Need to futz with it, obviously the blank Omit is doing something weird to the type that I don't understand but we need for the stubbing to work 😁

2023-05-16 21:08 UTC, Shadowfiend approved these changes
All set on the testing, let's land it!

2023-05-16 21:36 UTC, merged