Add header  in transaction details view
tahowallet/extension pull request #3387
Opened 2023-05-17 08:56 UTC by kkosiorowska

Closes #1167 

This PR adds a header to the transaction details view and solves the problem of missing header for the custom network. Changes:
-  Separate component for the activity icon
- Special hook to return activity details view
- Minor improvements

In addition, the problem with missing padding when the network does not have NFTs has been fixed, check the screenshots below.

### UI

**Before**
<img width="250" alt="Screenshot 2023-05-17 at 10 12 35" src="https://github.com/tahowallet/extension/assets/23117945/d73274dd-7afd-468e-8ca7-8e838043979b">

<img width="250" alt="Screenshot 2023-05-17 at 10 40 32" src="https://github.com/tahowallet/extension/assets/23117945/a8f03bb1-93bc-4158-8df4-eea643bf2676">

<img width="250" alt="Screenshot 2023-05-17 at 10 42 32" src="https://github.com/tahowallet/extension/assets/23117945/c59904c3-fcb3-4440-b2f2-00136f2395ac">

**After**
<img width="250" alt="Screenshot 2023-05-17 at 10 18 34" src="https://github.com/tahowallet/extension/assets/23117945/9f77f522-f3d6-45bc-a4fc-3893fbf05019">

<img width="250" alt="Screenshot 2023-05-17 at 13 52 32" src="https://github.com/tahowallet/extension/assets/23117945/68dbffd7-51d5-4c36-8112-adc5ddef4c34">

<img width="250" alt="Screenshot 2023-05-17 at 10 10 39" src="https://github.com/tahowallet/extension/assets/23117945/e5850599-ffb3-44be-a48c-5663cb11ba1b">

### To Test
- [x] Check top padding for the activity list when a network does not have NFTs.
- [x] Check the header for custom network. The link should be working properly.
- [x] check the header for default network. The link should be working properly.

Latest build: [extension-builds-3387](https://github.com/tahowallet/extension/suites/12979887290/artifacts/702340713) (as of Thu, 18 May 2023 07:07:45 GMT).

2023-05-17 11:02 UTC, Shadowfiend commented
Quick non-blocking note, but it looks like we might not be properly resolving the base asset symbol in the "Amount" field of transaction details (currently says "ETH" when based on the other stuff I see it should probably say "EVMOS").

2023-05-17 11:58 UTC, Shadowfiend requested changes
Left a few small nits and some broader context/future considerations. Have not tested yet, but I don't need to be primary reviewer here if someone else wants to take it to merge.

2023-05-17 11:58 UTC, Shadowfiend commented on ui/components/Shared/SharedActivityIcon.tsx
> +  | "contract_interaction"
I think we should be able to reuse the existing set here from `TransactionAnnotation["type"]`. This should let the type reflect new possibilities if/as we add them. 

Because of how the component is written below, new types would just default to the contract interaction icon (which feels like correct behavior).

2023-05-17 11:58 UTC, Shadowfiend commented on ui/pages/Wallet.tsx
> +                NETWORKS_SUPPORTING_NFTS.has(selectedNetwork.chainID),
It feels like it's probably time (after this PR) to move this to [`useSwitchablePanels`](https://github.com/tahowallet/extension/blob/116b51aa7a2ec3062571b100e6b6fde1e2924ac6/ui/hooks/index.ts#L71) and let the NFT container define its structure separately from the others instead of sprinkling these weird conditionals everywhere.

2023-05-17 11:58 UTC, Shadowfiend commented on ui/hooks/activity-hooks.ts
> +          ? i18n.t("wallet.activities.tokenReceived")
Since we're already in a book context, could we `useTranslation` and shorten these keys?

2023-05-17 11:58 UTC, Shadowfiend commented on ui/components/Wallet/WalletActivityListItem.tsx
> -  // TODO Replace this with better conditional rendering.
More idle/non-blocking thinking to externalize past knowledge/context:

Ironically my TODO here was that it would be better to have components that specialized based on type, similar to how the signing summaries work, rather than having a data structure that's trying to fit data about all render types within it. 

Now that we're sharing info between components I think this approach is marginally better, but I still don't love that the activity details type has to carry fields that don't apply equally to all activity types. It's one of the open problems for me around the whole `ActivityItem` structure.

2023-05-17 11:58 UTC, Shadowfiend commented on ui/hooks/activity-hooks.ts
> +  address: string
Would love a more descriptive name here. Maybe `activityInitiatorAddress`? This makes it clear that it's used as a reference for who initiated the activity. We could use the same variable name in the activity list item.

2023-05-17 12:04 UTC, kkosiorowska commented
> Quick non-blocking note, but it looks like we might not be properly resolving the base asset symbol in the "Amount" field of transaction details (currently says "ETH" when based on the other stuff I see it should probably say "EVMOS").

I have tested the solution for default and custom networks. But I forgot to upload one screenshot for EVMOS. It seems that everything is good. I have updated the task description. Thanks for noticing!

<img width="250" alt="Screenshot 2023-05-17 at 13 52 32" src="https://github.com/tahowallet/extension/assets/23117945/d4aa05a6-5027-480e-a1af-2fc25c346088">

2023-05-17 14:25 UTC, kkosiorowska commented on ui/components/Shared/SharedActivityIcon.tsx
> +  | "contract_interaction"
Great suggestion. To use `TransactionAnnotation["type"]` I had to slightly modify the type to extract the icons for send and receive activities. Please take another look.

2023-05-17 15:04 UTC, Shadowfiend commented on ui/components/Shared/SharedActivityIcon.tsx
> +  | "contract_interaction"
Looks awesome!

2023-05-17 15:15 UTC, Shadowfiend commented on ui/hooks/activity-hooks.ts
> +}
The reason we end up needing `as` here is that the `icon` field isn't constant in the `details` objects. I'd prefer to avoid `as` because the compiler wouldn't warn us if e.g. we set an `icon` that wasn't in `ActivityIconType`—by definition `as` skips actually checking that the type is correct. We could fix this by adding `as const` to all the icon assignments (e.g. `icon: "contract-interaction" as const`) and dropping `as ActivityViewDetails`, but I'd like to suggest instead we flip the structure here and set some base details that can then be `return`ed directly in the cases:

```suggestion
export default function useActivityViewDetails(
  activity: Activity,
  activityInitiatorAddress: string
): ActivityViewDetails {
  const { t } = useTranslation("translation", {
    keyPrefix: "wallet.activities",
  })

  const baseDetails = {
    recipient: activity.recipient,
    assetLogoURL: activity.assetLogoUrl,
    assetSymbol: activity.assetSymbol,
    assetValue: activity.value,
  }

  switch (activity.type) {
    case "asset-transfer":
      return {
        ...baseDetails,
        label: isReceiveActivity(activity, activityInitiatorAddress)
          ? t("tokenReceived")
          : t("tokenSent"),
        icon: isReceiveActivity(activity, activityInitiatorAddress)
          ? "asset-transfer-receive"
          : "asset-transfer-send",
      }
    case "asset-approval":
      return {
        ...baseDetails,
        label: t("tokenApproved"),
        icon: "asset-approval",
        assetValue:
          activity.value === INFINITE_VALUE
            ? t("infiniteApproval")
            : activity.value,
      }
    case "asset-swap":
      return {
        ...baseDetails,
        icon: "asset-swap",
        label: t("tokenSwapped"),
      }
    case "contract-deployment":
    case "contract-interaction":
    default:
      return {
        ...baseDetails,
        icon: "contract-interaction",
        label: t("contractInteraction"),
      }
  }
}
```

What do you think?

2023-05-17 15:35 UTC, Shadowfiend commented
Tested this, overall everything looks good. Let me know which of the two paths (`as const` vs the `...baseDetails` rewrite) you want to take in that last comment, and then I think we'll be good to merge 💪

2023-05-18 06:50 UTC, kkosiorowska commented on ui/hooks/activity-hooks.ts
> +}
I like the idea of using `baseDetails`. Let's improve it!

2023-05-18 06:51 UTC, VladUXUI reviewed
Added some nitpicking at pixels :D otherwise looking awesome!

2023-05-18 06:51 UTC, VladUXUI commented on ui/components/Wallet/WalletActivityDetails.tsx
> +            margin-right: 14px;
margin-right: 14px; should be 8px

2023-05-18 06:51 UTC, VladUXUI commented on ui/components/Wallet/WalletActivityListItem.tsx
> -            margin-left: 9px;
margin-left: 9px; should be 4px

2023-05-18 13:47 UTC, Shadowfiend approved these changes
Test drive checks out, Vlad's notes have been addressed, let's rock and roll.

2023-05-18 13:48 UTC, merged