Swap Transaction screen redesign
tahowallet/extension pull request #3392
Opened 2023-05-18 13:28 UTC by jagodarybacka

TODO:

- [ ] add price impact to the transaction screen
- [ ] make details panel component better
- [ ] cleanup SignTransactionDetailsPanel /  DetailsPanel - merge them into one

2023-05-22 17:44 UTC, Shadowfiend requested changes
For future reference, this would have been much easier to review as 3-4 separate PRs 😬 Dropping a quick review of the `truncateDecimalAmount` changes, which I love, and which I think can be split out to a PR by themselves fwiw.

I'll continue to move through the changes today.

2023-05-22 17:44 UTC, Shadowfiend commented on background/lib/utils/index.ts
> + *                        for sgnificant digits up to this point
```suggestion
 *                         for significant digits up to this point
```

2023-05-22 17:44 UTC, Shadowfiend commented on background/lib/utils/index.ts
> + * but look for significant digits in the decimal up to `maxDecimalLength`
I know “significant” implies this, but perhaps we should clarify that we will look past `decimalLength` up to `maxDecimalLength` if the number is <1.

2023-05-22 17:44 UTC, Shadowfiend commented on background/lib/tests/utils.unit.test.ts
> +]
I know it's going to be more verbose, but I strongly recommend reworking these as an object, without necessarily defining a separate type:

```typescript
type TruncateDecimalAmountType = {
  value: number | string
  decimalLength: number
  maxDecimalLength: number | undefined
  expected: string
}
```

You can then unpack this directly in the tests:

```typescript
    it.each(integersCases)(
       "given integer should return integer",
       ({ value, decimalLength, maxDecimalLength, expected }) => {
```

This'll make the test cases themselves a little easier to understand, I think.

2023-05-22 17:44 UTC, Shadowfiend commented on background/lib/utils/index.ts
> +  return hasSignificantDigits ? `${integer}.${decimalsTruncated}` : integer
Can we just clamp this using `maxDecimalLength`, as in:

```typescript
  const firstSignificantDecimalDigit =
    // If the integer component is nonzero...
    integer.length > 1 || integer[0] !== "0" ?
      // All decimal digits are significant.
      0 :
      // Otherwise, the first significant digit is the
      // first nonzero decimal digit.
      decimals.findIndex((digit) => digit !== "0")

  const decimalsTruncated = decimals.substring(
    0,
    Math.max(
      // Take the first significant digit, unless the max
      // allowable decimal length is shorter.
      Math.min(firstSignificantDecimalDigit, maxDecimalLength),
      // Take up to the first allowed significant digit,
      // unless the requested minimum decimal length is
      // longer.
      decimalLength
    )
  )

  return `${integer}.${decimalsTruncated}`
```

?

2023-05-22 17:44 UTC, Shadowfiend commented on background/lib/tests/utils.unit.test.ts
> +  [0.00123, 4, 5, "0.0012"],
It looks like we support strings for the `value` but never actually test that path. Might be worth adding a few test cases for those.

Also missing: I don't see a version of this that actually checks the max decimal length? Feels like we need to check `[0.0000123, 4, 5, "0.000001"]` or something like that.

2023-05-22 19:04 UTC, Shadowfiend commented on background/redux-slices/0x-swap.ts
> +  (state: { assets: AssetsState }) => state.assets,
Non-blocking: makes me twitch to pull state from a different slice inside a slice. I would rather we move this to its own selectors file to make it clear it's gluing stuff from multiple slices together (and it can wield the `RootState` type that way).

2023-05-22 19:06 UTC, Shadowfiend commented on background/redux-slices/0x-swap.ts
> +        estimatedPriceImpact: quote.estimatedPriceImpact
I was puzzled as to why we weren't already using this, but it looks like the feature is only a few months old. Nice!

That said, the way this is implemented on the 0x side (https://github.com/0xProject/0x-api/blob/63fd378c3fd198fd1760cd684763956defccfb55/src/services/swap_service.ts#L99 ) looks like it's using fixed-point math, so what do you think about using `parseToFixedPointNumber` to pull a `FixedPointNumber` here?

2023-05-22 19:12 UTC, Shadowfiend commented on ui/components/Signing/SignatureDetails/TransactionSignatureDetails/DetailsPanel.tsx
> +      )}
Not immediately blocking, but let's instead add a `TransactionAdditionalDetails` component here that can work exactly like `TransactionSignatureSummary`, specializing based on `type`.

This will also eliminate the need for `isSwapAnnotation`, and set us up for additional tidbits of extra info for other transaction types (e.g. imagine seeing the current balance and new balance for asset transfers).

2023-05-22 19:13 UTC, Shadowfiend commented on ui/_locales/en/messages.json
> +    },
For these, I think we've namespaced stuff under the [`signTransaction` key](https://github.com/tahowallet/extension/blob/2b115ee5849ef51bd0f3563a04d8a4f565e08db2/ui/_locales/en/messages.json#L635-L663).

2023-05-22 19:17 UTC, Shadowfiend commented on ui/components/SignTransaction/SignTransactionPanelCombined.tsx
> -import SignTransactionDetailPanel from "./SignTransactionDetailPanel"
This component can also go away actually, but I'll take care of that hehe.

2023-05-22 19:24 UTC, Shadowfiend commented on ui/components/Signing/SignatureDetails/TransactionSignatureDetails/DetailsPanel.tsx
> +/* eslint-disable react-hooks/exhaustive-deps */
Would love to find a way to kill this, btw. Probably not worth futzing with it right now though 🙈

2023-05-22 19:29 UTC, Shadowfiend commented on ui/components/Signing/SignatureDetails/TransactionSignatureDetails/TransactionSignatureSummary/SwapAssetSummary.tsx
> +        />
Beautiful 🤩

2023-05-23 14:12 UTC, jagodarybacka commented on background/lib/utils/index.ts
> +  return hasSignificantDigits ? `${integer}.${decimalsTruncated}` : integer
hmm, it's not passing tests in this form - leaving zeros in the decimal part but I'll take a second look if you think doing recursion here is too much 🙈

2023-05-23 17:04 UTC, jagodarybacka commented on background/redux-slices/0x-swap.ts
> +        estimatedPriceImpact: quote.estimatedPriceImpact
We are not getting that number with a huge precision and right now we are not doing much besides checking if we should display it and what color to use so to me it seems like it is ok to be as simple as possible

2023-05-23 20:14 UTC, Shadowfiend commented on background/lib/tests/utils.unit.test.ts
> +  { value: "0.00123", decimalLength: 0, maxDecimalLength: 5, expected: "0" },
I'm surprised by this one. Shouldn't it yield `0.00123`?

2023-05-23 20:40 UTC, Shadowfiend commented on background/lib/utils/index.ts
> +  return hasSignificantDigits ? `${integer}.${decimalsTruncated}` : integer
This was laziness on my part haha. The recursion isn't the only part, I just think we're ending up with too many conditionals here. This version passes tests and makes it a little clearer where we're making decisions based on max vs decimalLength vs significant digit I think:

```typescript
  const firstSignificantDecimalDigit =
    [...decimals].findIndex((digit) => digit !== "0") + 1

  const decimalTruncationLength =
    integer.length > 1 || integer[0] !== "0"
      ? // For a value >=1, always respect decimalLength.
        decimalLength
      : // For a value <1, use the greater of decimalLength or first
        // significant decimal digit, up to maxDecimalLength.
        Math.min(
          Math.max(decimalLength, firstSignificantDecimalDigit),
          maxDecimalLength
        )

  // If the truncation point includes no significant decimals, don't include
  // the decimal component at all.
  if (decimalTruncationLength < firstSignificantDecimalDigit) {
    return integer
  }

  const decimalsTruncated = decimals.substring(0, decimalTruncationLength)

  return `${integer}.${decimalsTruncated}`
```

Ultimately I'll leave it up to you if that feels clearer—feel free to pull it in or not!

2023-05-23 20:44 UTC, Shadowfiend commented on background/lib/tests/utils.unit.test.ts
> +  { value: "0.00123", decimalLength: 0, maxDecimalLength: 5, expected: "0" },
Answering my own question: no, but that's because we return early right now. I think that's a mistake:

```typescript
  if (decimalLength === 0) {
    return integer
  }
```

I think this should be `if (decimalLength === 0 && maxDecimalLength === 0)`.

2023-05-23 20:53 UTC, Shadowfiend commented on ui/components/Signing/SignatureDetails/TransactionSignatureDetails/TransactionSignatureSummary/SwapAssetDetails.tsx
> +  const { t } = useTranslation()
Probably can use `signTransaction.swap` as the `keyPrefix` here?

2023-05-23 20:59 UTC, Shadowfiend commented on background/lib/utils/index.ts
> +  maxDecimalLength = decimalLength
Incidentally we should probably add this parameter to the `truncateDecimalAmount` call in `SignTransactionTransferInfoProvider`!

2023-05-23 21:15 UTC, Shadowfiend reviewed
Still not quite done, but almost there. Left a couple more notes—I like how much removing the final quote has removed from our swap page state machine 😅

2023-05-23 21:15 UTC, Shadowfiend commented on ui/components/Swap/SwapQuoteBalanceChange.tsx
> +        }
Do we know whether the sell and buy colors here are other common colors in the design system, or if calling them trading-sell and trading-buy is the most general way to reference them?

2023-05-23 21:15 UTC, Shadowfiend commented on ui/pages/Swap.tsx
> +    const assets = selectSwapBuyAssets(state) as SwappableAsset[]
Phew, I feel like it is time to make `selectSwapBuyAssets` return actual `SwappableAsset`s:

```typescript
export const selectSwapBuyAssets = createSelector(
  (state: RootState) => state.assets,
  selectCurrentNetwork,
  (assets, currentNetwork) => {
    return assets.filter(
      (
        asset
      ): asset is SwappableAsset & {
        recentPrices: SingleAssetState["recentPrices"]
      } => {
...
```

2023-05-24 10:55 UTC, jagodarybacka commented on ui/components/Swap/SwapQuoteBalanceChange.tsx
> +        }
<img width="153" alt="image" src="https://github.com/tahowallet/extension/assets/20949277/d9f0f86d-b827-4fdf-bd70-5b57f2bab42a">
Green in Figma is called `trading/incoming", pink is not named at all, lmk if you have better name ideas 😉

2023-05-24 11:10 UTC, jagodarybacka commented on background/lib/tests/utils.unit.test.ts
> +  { value: "0.00123", decimalLength: 0, maxDecimalLength: 5, expected: "0" },
Hmm, I wrote that `if` that is early returning an integer when the `decimalLength = 0`, because that was in that function before these changes 🤔 
I think it is not the worst thing to do - if you want to get an integer then you don't care about the decimal part. If you care about the decimal part then you should at least set `decimalLength = 1` - because that util will cut decimal part if it will contain only zeros so you will get a nice integer anyway. What do you think about it?

2023-05-24 15:02 UTC, jagodarybacka commented
Alright so there is still a problem that goes like this - sometimes we are able to show $ price on the swap screen but on the transaction screen we are losing it. 

It happens because swaps screen is using [checkCurrencyAmount](https://github.com/tahowallet/extension/blob/swap-tx-redesign/background/redux-slices/0x-swap.ts#L360) that will fetch the prices if there are no recent prices saved on the asset. Transaction screen is using [saved recent prices](https://github.com/tahowallet/extension/blob/swap-tx-redesign/ui/components/Swap/SwapQuoteBalanceChange.tsx#L50) which may be empty for some assets.

I think we should ensure that if prices are fetched then they are saved/cached so we can avoid problems like that and just use one method to get $ price where needed instead of having multiple ways to do the same thing which is causing bugs and problems.

But I think it is not blocking to this PR so I'll undraft it and I can continue fixing that in the next PR.

2023-05-24 15:39 UTC, jagodarybacka commented on background/lib/utils/index.ts
> +  return hasSignificantDigits ? `${integer}.${decimalsTruncated}` : integer
Refactored + removed that exception for `decimalLength=0` case

2023-05-24 18:17 UTC, Shadowfiend commented on background/lib/tests/utils.unit.test.ts
> +  { value: "0.00123", decimalLength: 0, maxDecimalLength: 5, expected: "0" },
Appreciate it. Surprisingly complicated for a function that feels so straightforward conceptually!

2023-05-24 18:18 UTC, Shadowfiend commented on background/lib/utils/index.ts
> +  maxDecimalLength = decimalLength
… Lol. I guess I'm cleaning that up now before I embarrass myself again 😆

2023-05-24 18:22 UTC, Shadowfiend commented on ui/components/Swap/SwapQuoteBalanceChange.tsx
> +  const toAmount = truncateDecimalAmount(rawToAmount, 2, 8)
I think we do need to continue to use `toLocaleString`—in many ways I hate that we've got `truncateDecimalAmount` at all, because it makes assumptions about number format that aren't localizable.

We do have the tools to unify all of it by taking the number and then passing it to `toLocaleString`, or using [`formatToParts`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts) and dealing with the `fraction` component. That said, I don't think it's a pressing concern at the moment.

2023-05-24 18:26 UTC, Shadowfiend commented on ui/components/Swap/SwapQuoteBalanceChange.tsx
> +        }
What about using `-incoming` and `-outgoing`? It looks like there's Trading/Outgoing style but it's a slightly different color, we can check with Vlad on that.

2023-05-24 18:29 UTC, Shadowfiend commented
> I think we should ensure that if prices are fetched then they are saved/cached so we can avoid problems like that and just use one method to get $ price where needed instead of having multiple ways to do the same thing which is causing bugs and problems.
>
> But I think it is not blocking to this PR so I'll undraft it and I can continue fixing that in the next PR.

Agree across the board, love the thinking. One way to force-fetch prices that also updates the cache ✅ and pushing to a separate PR ✅

2023-05-25 02:20 UTC, Shadowfiend commented on ui/components/Swap/SwapQuoteBalanceChange.tsx
> +        }
Checked with Vlad here—indeed, `-outgoing` is meant to be the pink we're using here, just hasn't made it into the design system file. Let's use those two names unless we have a strong reason to diverge!

2023-05-25 02:52 UTC, Shadowfiend commented on background/lib/utils/index.ts
> +  maxDecimalLength = decimalLength
The new flow uses `localizedDecimalAmount`—which is unfortunately subject to the problem of not always showing the amount of precision we might prefer.

Bleh. Can't make myself go down that rabbit hole right now 😅

Anyway, I said I'd clean it up and I'm cleaning it up (#3404 😝).

2023-05-25 02:54 UTC, Shadowfiend commented on ui/utils/swap.ts
> +  // filter by current chain and better handle network-native base assets
I think this TODO no longer applies? ETH isn't special-cased, though we're letting through assets that are not known to be on this chain.

2023-05-25 02:54 UTC, Shadowfiend reviewed
I believe most of my concerns are cleared here, so going to move into testing tomorrow.

2023-05-25 22:14 UTC, Shadowfiend approved these changes
This looks awesome 🤩 Approving, but going to give @VladUXUI a chance to do some design QA before landing this. Let's rock and roll 🎸

2023-05-26 05:59 UTC, VladUXUI commented
This is working and looking awesome! No changes on my part!

2023-05-26 11:12 UTC, Shadowfiend commented
Lfg!

2023-05-26 11:15 UTC, merged