Drop the `AddressOnNetwork` parameter for token import
tahowallet/extension pull request #3426
Opened 2023-06-01 08:35 UTC by kkosiorowska

Closes https://github.com/tahowallet/extension/issues/3401

## What
The token import should not be associated with any account. The balance should be checked for all accounts so the overview reflects the full balance with that token (though only on the asset's network).

## UI

https://github.com/tahowallet/extension/assets/23117945/2ed23346-7f79-4acf-aeb4-acad5dbbc3dd

## To Test
Accounts that have two of the same token(GGBoxs.com) are: 
- `0x208e94d5661a73360d9387d3ca169e5c130090cd`
- `0x63cf5f22c3719391e0014584bad67ecba6b9f98b`

Test token contract - `0xcf68f02d7dD6a4642AE6a77f6A3676D0CBC834c9`

To test the solution for the above data, you should first remove the token in order to add it again.

- [x] Try to import a custom token and check that the balances have been updated for all accounts.

## Testing Env

```
SUPPORT_UNVERIFIED_ASSET=true
```

Latest build: [extension-builds-3426](https://github.com/tahowallet/extension/suites/13403099239/artifacts/734005392) (as of Tue, 06 Jun 2023 10:47:15 GMT).

2023-06-01 18:46 UTC, Shadowfiend requested changes
Couple of comments on the details, but the change looks good. Need to test drive it once these are addressed.

2023-06-01 18:46 UTC, Shadowfiend commented on background/services/indexing/index.ts
> +    )
Wondering if we should `await` this or not. Which of these two sentences do we think is more accurate:

- `importCustomToken` is finished when we've started tracking the token AND all balances have been retrieved.
- `importCustomToken` is finished when we've started tracking the token and we have initiated the retrieval of all balances.

Another layer of looking at it is failure modes; should `importCustomToken` fail if:

- The token could not be added to our tracked tokens?
- We failed to look up what accounts we're tracking on the token's network?
- We failed to look up the token's balance for those accounts?

My sense here is that we want:
- `importCustomToken` to complete once all token balance retrievals complete (this is in line with how we handle balance lookups in the rest of the indexing service).
- `importCustomToken` to fail *only if we couldn't add the token by contract*. Otherwise, we could end up with a weird state where the token is being tracked, but we've maybe surfaced an error to the user.

To this end, I *think* (but please feel free to chime in if this doesn't feel right!) that we want to wrap the new code (`getAccountsToTrackByNetwork` + `retrieveTokenBalances`) in a `try`/`catch`, and we want to switch from `Promise.all` (which returns if any of the promises fails, as soon as that promise fails) to `Promise.allSettled` (which will return after all promises have completed, successfully or not).

2023-06-01 18:46 UTC, Shadowfiend commented on background/services/indexing/index.ts
> +    network: EVMNetwork
Unless I'm mistaken, here (and in the full call stack leading to here), we don't actually need this parameter, because the asset carries a `homeNetwork` that we're already using in `addTokenToTrackByContract` and serves the same function. In fact, this network is the same one being passed in here:

https://github.com/tahowallet/extension/blob/d885f915b49941c8d7628985ed8afd756f52b199/ui/pages/Settings/SettingsAddCustomAsset.tsx#LL212

2023-06-02 11:55 UTC, kkosiorowska commented on background/services/indexing/index.ts
> +    )
I agree, this makes a lot of sense. I have noticed that when we have more accounts importing the token takes a longer time. I decided to disable the button to add an asset for the duration of the token import.

2023-06-02 20:35 UTC, hyphenized commented on background/services/indexing/index.ts
> +    )
Alternatively, could we consider importing done once we've retrieved the balance for the current address and queued a lookup for the rest of the balances to happen in the background?

2023-06-05 02:38 UTC, Shadowfiend requested changes
Only one blocker around when we should be redirecting!

2023-06-05 09:45 UTC, kkosiorowska commented on background/services/indexing/index.ts
> +      )
Let's fix it in https://github.com/tahowallet/extension/issues/3435

2023-06-05 10:46 UTC, kkosiorowska commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +      history.push("/")
I think showing the right message will be a good solution.
@VladUXUI  Do you have any suggestions as to how it should sound?  I think we could create such a global message and use it when something goes wrong.

2023-06-05 15:18 UTC, Shadowfiend commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +      history.push("/")
I believe these are the ways this could fail:

- We somehow fail to resolve the details of the token (e.g. the decimals of precision, etc), which we have to look up on-chain or via an Alchemy helper.
- We fail to resolve initial balance information for the token.

Most general version of it is “network issues”—but the outcome is that the custom asset has *not* been added. The user could try again with the same asset, or they could cancel, depending on their preference. I don't know how specific we can get in the error though, unfortunately (i.e., we can probably say “Failed to look up token details” but not much more).

2023-06-05 15:41 UTC, kkosiorowska commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +            isLoading={loading || isImportingToken}
Fixed

2023-06-05 15:41 UTC, kkosiorowska commented on background/services/chain/db.ts
> +  async getAccountsToTrackByNetwork(
Fixed

2023-06-06 06:36 UTC, VladUXUI commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +      history.push("/")
> Failed to look up token details

This sounds like a good error message to me, at least it provides some sort of context, even if not next steps as well.
Ideally we could share next steps or how to fix, but since we don't know, i'm good to the error above

2023-06-06 10:48 UTC, kkosiorowska commented on ui/pages/Settings/SettingsAddCustomAsset.tsx
> +      history.push("/")
I've added a message. I simulated the error and it looks like the following:

https://github.com/tahowallet/extension/assets/23117945/ad7380cd-9036-4132-9457-0790cb1b80ec

2023-06-06 11:11 UTC, Shadowfiend reviewed
Kk code looks good, haven't had a chance to test yet though. If anyone beats me to it please feel free to merge!

2023-06-06 13:38 UTC, merged