DSL connection: Add new default wallet toggle top bar
tahowallet/extension pull request #3448
Opened 2023-06-06 05:08 UTC by Shadowfiend

To do this, we also restructure the top bar and, in the process,
the tab bar's management in `CorePage`. These give us the space
and tools to set up the new `DAppConnection` component, which now
contains the default wallet toggle and the current dApp connection's
information.

<img width="437" alt="Screenshot 2023-06-06 at 01 02 09" src="https://github.com/tahowallet/extension/assets/8245/24d2da8a-be84-4a76-871d-c709b6d1764b">

2023-06-08 23:12 UTC, hyphenized requested changes
Looks good, left some comments. Are we reverting the color changes in this PR or do we want to do that in the other one and merge that here?

2023-06-08 23:12 UTC, hyphenized commented on ui/components/Core/CorePage.tsx
> +      {hasTopBar ? <TopMenu /> : <></>}
Why not use the shorthand `condition && <Component />`? n/b

2023-06-09 00:54 UTC, Shadowfiend commented on ui/pages/Swap.tsx
> +      </>
Nope! Eventually this should have CorePage around it, but CorePage needs some changes still to get there (I prototyped a bunch of this stuff in #2663).

2023-06-09 00:55 UTC, Shadowfiend commented on ui/components/Shared/SharedToggleButton.tsx
> +}
That's not really what we've been doing... If we want to do that we should systematically convert to it.

2023-06-09 01:08 UTC, Shadowfiend commented on ui/public/index.css
> +.fade-out {
That's my bad. I mean my answer is always kebab case unless the syntax does not allow, but I think the vast majority of our code uses... snake case lol. So I should probably convert fadeIn and use that here as well.

2023-06-09 01:08 UTC, Shadowfiend commented on ui/components/DAppConnection/DAppConnection.tsx
> +  )
🤦😅👌

2023-06-09 01:09 UTC, Shadowfiend commented on ui/components/Shared/SharedToggleButton.tsx
> +            background-color: ${offColor ?? "var(--green-40)"};
I love that and really want to do it moving forward across our components. I would rather not add extra cycles to this work at this moment to do it in this component though 😅

2023-06-09 01:11 UTC, Shadowfiend commented on ui/components/DAppConnection/DAppConnection.tsx
> +    initPermissionAndOrigin()
I'm trying not to refactor this piece here because it shouldn't be in an effect at all tbh, it should be relayed from the background. So it's a bigger piece of work.

2023-06-09 01:19 UTC, Shadowfiend commented on ui/components/Core/CorePage.tsx
> +      {hasTopBar ? <TopMenu /> : <></>}
I have deep and abiding dislike for Boolean punning in typescript (including `!!`). I'm mad I didn't have a linter flag in place a year ago to prohibit it across the codebase tbh. In general shorthand is worse than being explicit about intent. 

/rant 😅

2023-06-09 02:09 UTC, Shadowfiend commented on ui/components/Shared/SharedToggleButton.tsx
> +}
To wit:
```sh
shadowfiend@theano ~/g/t/extension /cable-connection> ag -l defaultProps | wc -l
      20
```

2023-06-09 02:17 UTC, Shadowfiend commented on ui/public/index.css
> +.fade-out {
`fadeIn` touches a lot of components, so rather than add extra testing burden on this PR I'm going to do that rename in a separate one.

2023-06-09 02:34 UTC, Shadowfiend commented on ui/components/Core/CorePage.tsx
> +            height: 100%;
Yeah, I remember having to disentangle some serious stuff when I tackled this a few months ago. I think this is the least bad option without going deep on the DOM (which I'm planning to do next week), since the bar space situation has changed with the new work.

Are there any places where this seems egregious right now?

2023-06-09 02:39 UTC, Shadowfiend commented on ui/public/index.css
> +  --trophy-gold: #ed9a26;
f0db09c9120b9e7304fd1522da1986cd27996388

2023-06-09 02:39 UTC, Shadowfiend commented on ui/public/index.css
> +.fade-out {
871de3bd67f13eb7e32a08042053918e1e9a195e

2023-06-09 02:39 UTC, Shadowfiend commented on ui/components/DAppConnection/DAppConnection.tsx
> +  )
6c6dd1ae982446ba8928709166466ff6ea4a314e

2023-06-09 02:39 UTC, Shadowfiend commented on ui/components/Shared/SharedToggleButton.tsx
> +  /**
31c44ad375508f1469b76834a808c6950655c039

2023-06-09 02:41 UTC, Shadowfiend commented on ui/components/DAppConnection/DAppConnectionDefaultToggle.tsx
> +  const hasDetectedOtherWallets = true
https://github.com/tahowallet/extension/commit/45a45a38ac2b13e39dfea29bfa66e9c8a58ca818

2023-06-09 02:41 UTC, Shadowfiend commented
Made all of the changes I'm down for rn, but happy to discuss the other stuff further if desired!

2023-06-09 04:03 UTC, hyphenized commented on ui/components/Shared/SharedToggleButton.tsx
> +}
Ahh yeah there are also a few places where we're doing both. My reasoning is that there's no real advantage to use default props over parameter defaulting and it doesn't play well with typescript ( one known issue with forwarding refs ). Default props is also getting deprecated but, while I don't think it's happening anytime soon I feel this just provides another place where we could miss out potential bugs. If we're going back to `defaultProps` then I suggest we should create an issue like #1120.

2023-06-09 04:03 UTC, hyphenized commented on ui/public/index.css
> +  animation: fade-out ease-out var(--fade-ou-durationt, 250ms);
```suggestion
  animation: fade-out ease-out var(--fade-out-duration, 250ms);
```

2023-06-09 10:33 UTC, Shadowfiend commented on ui/components/Shared/SharedToggleButton.tsx
> +}
I would love an issue--but to move *away* from defaultProps. I just don't want to do it inconsistently, I think using the language feature rather than the framework feature is the right call. 

For context, IIRC when we first built things out we had issues with typing and linting and param defaults which, combined with how common defaultProps was in the react literature, convinced us to stick to that to start with.

2023-06-09 13:58 UTC, Shadowfiend commented on ui/public/index.css
> +  animation: fade-out ease-out var(--fade-ou-durationt, 250ms);
Obviously I vimed too hard on this one 😆

2023-06-12 00:58 UTC, hyphenized approved these changes
🚢 🚢 🚢

2023-06-12 01:01 UTC, merged

2023-06-13 15:03 UTC, kkosiorowska commented
I noticed one small style issue caused by these changes when the feature flag is enabled. I just reported it. https://github.com/tahowallet/extension/issues/3474

2023-06-13 15:22 UTC, Shadowfiend commented
Good catch thank you!