Restructure the settings page
tahowallet/extension pull request #3450
Opened 2023-06-06 16:34 UTC by kkosiorowska

Closes https://github.com/tahowallet/extension/issues/3414

## What
Currently, the settings page includes more elements. Elements should be grouped for better clarity.

## UI

Before
<img width="381" alt="Screenshot 2023-06-06 at 18 32 08" src="https://github.com/tahowallet/extension/assets/23117945/4a3dd8d1-dba7-419b-a334-5351dd6a3f8a">

After
<img width="373" alt="Screenshot 2023-06-06 at 18 31 50" src="https://github.com/tahowallet/extension/assets/23117945/4e8e168c-00d9-4f1f-be2e-c766374cd4be">

## To Test
- [ ] Go to the settings page and check that items are grouped.

2023-06-06 17:24 UTC, hyphenized requested changes
This looks good to go, just a few small nits

2023-06-06 17:24 UTC, hyphenized commented on ui/utils/lists.ts
> +}
Sweet! Just a small nit, we can remove the `boolean` union from the parameter as it is implied that T can be a `boolean`, we should also fix the return type here.

```suggestion
export const excludeFalsyValues = <T>(items: T[]): Exclude<T, boolean>[] => {
  return items.filter((item): item is Exclude<T, boolean> => !!item)
}
```

2023-06-06 17:24 UTC, hyphenized commented on ui/pages/Settings.tsx
> +            color: var(--green-20);
Is this the right shade? It looks a bit darker in figma

Current: 
![image](https://github.com/tahowallet/extension/assets/28708889/a78acb36-53b7-4aee-8e17-8d1afd4eaf50)
Design:
![image](https://github.com/tahowallet/extension/assets/28708889/55e0137a-88bd-4ad5-9126-78ca6b54e137)

2023-06-06 17:24 UTC, hyphenized commented on ui/_locales/en/messages.json
> +      "helpCenter": "Help Center"
```suggestion
      "walletOptions": "Networks & assets",
      "helpCenter": "Help center"
```

2023-06-06 17:38 UTC, Shadowfiend commented on ui/pages/Settings.tsx
> +  }).map(({ title, items }) => ({ title, items: excludeFalsyValues(items) }))
Rather than subjecting the entire list to feature-flag-related action (which would likely stay well after the feature flags die due to the fact that they're not obviously related), I would prefer to continue using the paradigm we've been using of spreading a potentially-empty array:

```typescript
   ...(isEnabled(FeatureFlags.SUPPORT_MULTIPLE_LANGUAGES) ? [languages] : [])
```

In fact, we could introduce a utility for this, as we do similar things in a few places:

```typescript
  wrapIfEnabled<T>(flag: FeatureFlagType, valueToWrap: T): [T] | [] {
    return isEnabled(flag) ? [valueToWrap] : []
  }

  // ...

  [
    // ...
    ...wrapIfEnabled(FeatureFlags.SUPPORT_MULTIPLE_LANGUAGES, languages),
    ...wrapIfEnabled(FeatureFlags.SUPPORT_ACHIEVEMENTS_BANNER, notificationBanner),
  ]
```

2023-06-06 18:32 UTC, Shadowfiend commented on ui/pages/Settings.tsx
> +            color: var(--green-20);
I just discovered most of our color variables don't match the design system. Will fix in the dApp Connection work, so let's leave this one alone.

2023-06-07 08:37 UTC, VladUXUI reviewed
Looking good!
Just one little change, non blocking

2023-06-07 08:37 UTC, VladUXUI commented on ui/pages/Settings.tsx
> +            color: var(--green-20);
color: var(--green-20); Let's change to 
color: var(--green-40)

In my design the main content is white and title are 20. But i forgot we have mouse over on most items, so let's change the title to 40 and should have same results

2023-06-12 08:30 UTC, kkosiorowska commented on ui/utils/lists.ts
> +}
It is no longer used.

2023-06-14 11:39 UTC, hyphenized approved these changes
🚢

2023-06-14 11:43 UTC, merged