Route transactions through Flashbots
tahowallet/extension pull request #3455
Opened 2023-06-07 14:16 UTC by jagodarybacka

WIP - working happy path, need to save the setting in the database, think through the redux and fallback provider connection, add custom params to the RPC

2023-06-09 02:52 UTC, Shadowfiend commented
> do we want to add a tooltip to explain a bit more what this toggle does?

My 2c here is yes, something like:

> Sends all transactions through Flashbots to protect against frontrunning and shares MEV back with you. This can leak some information about your transactions to searchers, see [the Flashbots documentation](https://docs.flashbots.net/flashbots-protect/rpc/mev-share#stable-configuration) for more.

I would also consider making the “Use Flashbots RPC” toggle be “Use Flashbots RPC by default” since we allow toggling per-tx.

2023-06-09 03:00 UTC, Shadowfiend commented
Haven't had a chance to go deep here quite yet, but left some initial thoughts above. Excited to see this working!

2023-06-09 10:28 UTC, jagodarybacka commented
> Re: Goerli: only if it's trivial, and if so we should add Sepolia as well.

Seems like they only support Goerli but the docs are not saying anything really about it, I can't even find info if I have to use the same endpoint or a different one to send to the testnet. Maybe let's drop it for now.
![image](https://github.com/tahowallet/extension/assets/20949277/6f0afd75-95d8-4e20-9723-d0b35ed13a59)

Re: filtering methods

yeah not sure if that will be needed for other RPCs but I would like to avoid getting rate limited by Flashbots so I think only routing transactions through them is the best option. We can ignore that when we will decide to implement user-imported RPCs.

2023-06-09 11:02 UTC, Shadowfiend commented
It does look like Sepolia is supported from various other parts of their docs. Since the instructions for Goerli are this:

> Add https://rpc-goerli.flashbots.net with a chainID of 5 and currency of ETH.

We could just see if this works equivalently on Sepolia. Agree there's no need to burn time on it rn though.

2023-06-09 11:09 UTC, jagodarybacka commented
oh thanks, their search bar wasn't helpful at all 🙈

2023-06-12 10:04 UTC, jagodarybacka commented
@VladUXUI Can you take a look at this build and let us know what would you like to change regarding UX?

2023-06-14 14:46 UTC, VladUXUI commented
Took a look it this and did some digging in documentation.
As far as i understand, send / approve and other simple interactions don't go through Flashbot mempool, i mean Flashbot automatically send these to the public mempool.
Would it then make sense to only have Flashbots in transactions that need actual protection?

This is so users don't think they will get MEV from send/approve transactions.

2023-06-14 14:46 UTC, VladUXUI commented
Also, what is the benefit of having the toggle in each transaction?

2023-06-15 08:56 UTC, kkosiorowska reviewed
I haven't tested some minor comments.

2023-06-15 08:56 UTC, kkosiorowska commented on background/main.ts
> +      const flashbotsProvider = makeFlashbotsProvider()
I wonder if we shouldn't move this to `addCustomProvider`  method.

2023-06-15 08:56 UTC, kkosiorowska commented on background/redux-slices/ui.ts
> +    await main.toggleFlashbotsProvider(value)
Should the order not be reversed? What I mean is that the update of the UI always occurs after the update in the db.

2023-06-15 08:56 UTC, kkosiorowska commented on background/services/chain/serial-fallback-provider.ts
> +  chainID: string,
It is not used anywhere.

2023-06-15 08:56 UTC, kkosiorowska commented on .env.defaults
> +SUPPORT_FLASHBOTS_RPC=false
The description for the dev panel is missing in `messages.json`. We often forget about it but don't use the dev panel probably at all. We could somehow solve this issue.

2023-06-15 10:45 UTC, jagodarybacka commented on background/main.ts
> +      const flashbotsProvider = makeFlashbotsProvider()
Hmm, I wanted to keep service agnostic about Flashbots

2023-06-15 10:47 UTC, jagodarybacka commented on .env.defaults
> +SUPPORT_FLASHBOTS_RPC=false
Yeah at this point I would vote to drop that feature as a whole as it is causing a burden without adding much value

2023-06-15 10:56 UTC, jagodarybacka commented on background/services/chain/serial-fallback-provider.ts
> +  chainID: string,
I wanted to make it follow the same arguments set as `alchemyOrDefaultProvider` but maybe it doesn't make that much sense 😂

2023-06-15 11:22 UTC, Shadowfiend commented on .env.defaults
> +SUPPORT_FLASHBOTS_RPC=false
Let's double check no one's life depends on it in discord but then yeah I'm ready to kill it with fire.

2023-06-15 11:35 UTC, Shadowfiend reviewed
Couple of thoughts as I finally get to this, sorry for the delay. More to come!

2023-06-15 11:35 UTC, Shadowfiend commented on background/constants/networks.ts
> +export const ALCHEMY_RPC_METHOD_PROVIDER_ROUTING = {
Non blocking: is this used outside of chain service? It seems like that's where it belongs...

2023-06-15 11:35 UTC, Shadowfiend commented on background/main.ts
> +      const flashbotsProvider = makeFlashbotsProvider()
This isn't really making the provider right? It's returning the descriptor/provider creator for it. There's a naming thing here I'd like to get right, though I don't think we necessarily need to block on it.

2023-06-15 11:35 UTC, Shadowfiend commented on background/services/chain/serial-fallback-provider.ts
> +  customRpc?: { rpcUrl: string; supportedMethods?: string[] }
We should name the type for custom RPCs--perhaps `RpcConfig`? 

Also, why not change `rpcUrls` to `rpcConfigs: RpcConfig[]` or so? There doesn't seem to be much difference between the two.

2023-06-16 18:01 UTC, Shadowfiend commented on background/redux-slices/ui.ts
> +    await main.toggleFlashbotsProvider(value)
To be clear, but not blocking: we should update the db, and the service should propagate that update to the UI. Preferences are a little wobbly right now in this regard, but that's the ideal data flow through the system.

2023-06-20 07:08 UTC, VladUXUI commented
Hopefully is not too late, but could we change toggle inside transaction to a checkmark instead of a toggle?
Toggles are generally used for more permanent states, and this is a situational one.
Maybe something like this?
<img width="380" alt="image" src="https://github.com/tahowallet/extension/assets/80846886/4f9997c7-8636-46ac-a533-5afe2b90981e">

2023-06-22 14:58 UTC, jagodarybacka commented
We don't need a feature flag here I think, right?

2023-06-22 19:58 UTC, Shadowfiend commented
I think we probably should have merged sooner and used the feature flag, but since we didn't do that, I think the flag has become unnecessary.

2023-06-23 07:49 UTC, kkosiorowska commented on ui/components/Signing/SignatureDetails/TransactionSignatureDetails/DetailsPanel.tsx
> +              />
While testing the changes for https://github.com/tahowallet/extension/pull/3495 I noticed one thing. The empty space does not have a pointer cursor but changes the state of the checkbox. I wonder if in this case, only the checkmark should be clickable.

https://github.com/tahowallet/extension/assets/23117945/67e8b6b1-dbf2-4df8-9faf-7511ac4d2d5a

2023-06-23 07:57 UTC, jagodarybacka commented on ui/components/Signing/SignatureDetails/TransactionSignatureDetails/DetailsPanel.tsx
> +              />
I like that the checkbox label is clickable tbh, that's the default checkbox behavior iirc, I'll just fix that cursor.

2023-06-23 13:42 UTC, Shadowfiend commented on ui/components/Signing/SignatureDetails/TransactionSignatureDetails/DetailsPanel.tsx
> +              />
Labels should always trigger (for buttons) or focus (for fields) their labeled items—but agree the cursor would be a nice touch.

2023-07-04 09:46 UTC, kkosiorowska commented
Migration works correctly ✅

2023-07-14 11:14 UTC, kkosiorowska requested changes
I spent some time testing Flashbots. It seems to work fine in almost all cases. Some notes:

- We use Flashbots when the checkbox is disabled. Steps to reproduce:
1. Send transaction using flashbots
2. Change the network and send the transaction from the new network.
3. Back to the Ethereum network and try to send transaction when the checkbox is disabled. 



https://github.com/tahowallet/extension/assets/23117945/975f9420-dcc6-428b-a296-b5112f146edd

- I can't do the swap using Flashbots. I have this problem also when using Uniswap dApp.
https://github.com/tahowallet/extension/assets/23117945/243b70d5-bad2-46d4-be87-1c1d10dda727



https://github.com/tahowallet/extension/assets/23117945/2fe172bc-2dd0-4224-bdee-ece399f34022

2023-07-14 11:14 UTC, kkosiorowska commented on ui/pages/Settings.tsx
> +    tooltip: () => (
Non-blocking
After adding the tooltip property and merge we should also use this for `autoLockSettings`

2023-07-16 17:00 UTC, beemeeupnow commented
> * I can't do the swap using Flashbots. All my transactions are dropped. I have this problem also when using Uniswap dApp.

I did not encounter the issue with Uniswap.

It seems the current build may not have a 0x API key so I could not test the built-in swap.

2023-07-16 17:20 UTC, Shadowfiend commented
> It seems the current build may not have a 0x API key so I could not test the built-in swap.

This changed this week and we haven't gotten a chance to add a dev key for the dev builds, sorry folks.

2023-07-17 19:03 UTC, Shadowfiend commented on background/main.ts
> +          await this.autoToggleFlashbotsProvider()
Should we be doing this in `handleAndClear` as well?

2023-07-17 19:11 UTC, Shadowfiend commented on background/main.ts
> -          this.autoToggleFlashbotsProvider()
Not blocking: this whole thing makes me think `autoToggleFlashbotsProvider` behavior really shouldn't be in `main`. The flashbots stuff probably needs to be a first-class concept in the chain service itself, maybe as a generic “temporarily use this RPC for this transaction” thing. The RPC would be included as an optional parameter in the `broadcastSignedTransaction` call so that its usage is atomic rather than mutating global state that is subject to race conditions.

2023-07-18 07:25 UTC, kkosiorowska approved these changes
Looks like the issue has been solved :white_check_mark: Today I had no more problems with the swaps on Uniswap. But still a few of my transactions have been dropped, but I don't think this is due to these changes.

2023-07-18 12:52 UTC, kkosiorowska commented on background/main.ts
> -          this.autoToggleFlashbotsProvider()
Let's make it this way. Please create a task for the refactor.  We are ready for merge :rocket:

2023-07-18 12:57 UTC, merged