Transaction replacement - Allow speeding up transactions
tahowallet/extension pull request #3456
Opened 2023-06-08 06:27 UTC by hyphenized

Allows speeding up transactions

## Testing Env

```
SUPPORT_TRANSACTION_REPLACEMENT=true
```

## To Test
- [ ] Send a transaction
- [ ] On the activity list, open up the details slide up for the pending transaction that was just made, click on speed up and sign the transaction prompt that follows.
- [ ] The original transaction should not display in the activity list once the replacement transaction succeeds

2023-06-08 11:01 UTC, kkosiorowska reviewed
I haven't tested it yet but the first few comments at first glance.

2023-06-08 14:17 UTC, kkosiorowska reviewed
Some visual issues:
- [ ] Address not displaying correctly
<img width="378" alt="Screenshot 2023-06-08 at 15 06 05" src="https://github.com/tahowallet/extension/assets/23117945/9083b4ed-e63f-447f-8ecd-ed03df47aca9">

- [ ] Dropped should be in red colour
<img width="377" alt="Screenshot 2023-06-08 at 15 18 48" src="https://github.com/tahowallet/extension/assets/23117945/a3053d67-f904-483d-a4f9-07cd4dbd82cb">

I wonder if the last element should have a bottom border. 🤔

<img width="381" alt="Screenshot 2023-06-08 at 15 24 32" src="https://github.com/tahowallet/extension/assets/23117945/079c1438-d5ef-4c7b-a5ee-84d2c15d4cfb">

2023-06-09 12:26 UTC, jagodarybacka reviewed
Couple of comments, haven't tested yet

2023-06-09 12:26 UTC, jagodarybacka commented on background/main.ts
> +    return [getActivityDetails(enrichedTransaction)]
I don't see a point in wrapping this with an array - seems like we are destructuring it later anyway right?

2023-06-09 12:26 UTC, jagodarybacka commented on background/redux-slices/activities.ts
> +          request.hash === transaction.hash &&
in the other place we are checking tx's author and nonce - so what should we check to know if it is a replacement tx? 🤔

2023-06-09 12:26 UTC, jagodarybacka commented on ui/components/Wallet/WalletActivityDetails.tsx
> +                : "....."}
Maybe let's use a skeleton loader for this whole panel instead or just a status text, these dots are looking weird IMO

2023-06-09 13:39 UTC, Shadowfiend commented on background/redux-slices/utils/activities-utils.ts
> +type TransactionStatus = "pending" | "dropped" | "failed" | "completed"
We've generally avoided using enums in the past as they don't bring much to the table compared to simple type unions like this one (other than extra verbosity 😅). Is there something in particular we want to get out of a need them?

2023-06-09 13:56 UTC, Shadowfiend commented on background/redux-slices/activities.ts
> +          request.hash === transaction.hash &&
A tx is a replacement if it's a matching nonce, fwiw—but sometimes the previous version of the nonce will get included in the block if it was put into a block by a miner before the replacement made it.

2023-06-09 13:56 UTC, Shadowfiend commented
@hyphenized can you put some more high-level details on approach & changes in the PR description when you get a chance?

2023-06-09 14:23 UTC, jagodarybacka commented on background/redux-slices/utils/activities-utils.ts
> +type TransactionStatus = "pending" | "dropped" | "failed" | "completed"
Ah I just like their syntax and the fact that I know just looking at it that it is some defined structure, not just a string, I don't have to wonder if this should be for example translated somewhere or not. Not a super strong preference anyway 😉

2023-06-09 17:47 UTC, Shadowfiend commented on background/redux-slices/utils/activities-utils.ts
> +type TransactionStatus = "pending" | "dropped" | "failed" | "completed"
Ah yeah, fair, this is def a situation where I lean on the editor/language server a lot. I hear your point though, esp the ability to easily identify that something should be translated. Will ponder that a little bit.

2023-06-12 04:01 UTC, hyphenized commented on background/redux-slices/activities.ts
> +    const TxRequest = {
Good catch

2023-06-12 04:03 UTC, hyphenized commented on background/redux-slices/activities.ts
> +      type: tx.type as 0,
Thought this one was a bug 😅. Turns out this wasn't considered valid because `signer.sendTransaction` uses the `TransactionRequest` type from ethers which does not accept `null` values.

2023-06-12 04:03 UTC, hyphenized commented on ui/components/Wallet/WalletActivityDetails.tsx
> +    keyPrefix: "wallet",
Tried this one but if we needed to add some common translation here we would end up with `activitiesT`, `activityDetailsT` and `sharedT` 😬

2023-06-12 04:06 UTC, hyphenized commented on background/redux-slices/activities.ts
> +      throw new Error("Cannot speed up transaction without a valid gas price")
Agree, another concern I have here is related to block times and chains without mempool, for example it doesn't make sense to show the option to speed up transactions on Optimism, and, on Polygon we get fast enough block times that most attempts to speed up result in the replacement transaction being dropped. Maybe we could use block times or check if we have lower than average gas fees to improve UX a bit here 🤔 .

2023-06-12 04:13 UTC, hyphenized commented on background/redux-slices/utils/activities-utils.ts
> +type TransactionStatus = "pending" | "dropped" | "failed" | "completed"
Yeah I think these should go into an enum, I ended up reverting this after having conflicting thoughts over similar values for activities. I agree that enums are verbose although one redeeming quality I think would be that with an union we'd have to do an intersection to get one of the members as a fixed type without losing the reference to the group, like the following:

```ts
type A = "a" | "b"

type B = {
  // something is "a", if we remove "a" from the type above this becomes never
  something: A & "a"
}
```

Whereas with enums we can do:
```ts
enum A {
  a,
  b,
}

type B = {
  // If we remove "a" from the enum above we get an error here instead of `never`
  // as the type for something
  something: A.a
}
```

One "downside" with these is that if we use string values for this enum then we have to reference the enum members directly, strings/constants do not work.

2023-06-12 04:14 UTC, hyphenized commented on ui/components/Wallet/WalletActivityDetails.tsx
> +  const isReadOnlyAccount = currentSigner.type === "read-only"
That does work but it could lead to sneaky bugs if the selector ever returns a different object with a similar structure

2023-06-12 04:15 UTC, hyphenized commented on background/main.ts
> +    return [getActivityDetails(enrichedTransaction)]
This is related to #3333, for some reason types work correctly if you wrap the return type in a tuple.

2023-06-12 04:16 UTC, hyphenized commented on background/services/chain/index.ts
> +        networkTransactions.filter(
Probably if we had an index for `nonce + from + network` but even then I'd say the performance difference would be negligible for most users. If you're interested in digging deeper you can run a few tests here: https://jsfiddle.net/dfahlander/xf2zrL4p

2023-06-12 04:33 UTC, hyphenized commented on background/redux-slices/activities.ts
> +          request.hash === transaction.hash &&
I think this is bad naming on my part, this logic will run a few times, specifically for: pending transactions, completed transactions and once again for these two if they've been enriched. Here we're checking if we're already tracking it to get info about the transaction it's replacing so that we can remove it from the list if the replacement has been mined. I'll add this as a comment.

2023-06-12 11:30 UTC, jagodarybacka commented on background/redux-slices/activities.ts
> +      throw new Error("Cannot speed up transaction without a valid gas price")
I think we should make an allowlist for the speedup tx button 🤔

2023-06-12 11:55 UTC, jagodarybacka commented
- [ ] I'm not able to scroll the activity slideup 
![image](https://github.com/tahowallet/extension/assets/20949277/9dee2dab-18f5-4c85-92a4-d452209048d1)

- [ ] if you browse activities by opening slideup one by one, then fields show previous values for a sec. I think we should use skeleton loaders and clean up the previous values in the slideup.

https://github.com/tahowallet/extension/assets/20949277/b6aa88ce-ea56-4410-817a-996701a01d0f


- [ ] on the list tx is listed as pending while we already know it was dropped

https://github.com/tahowallet/extension/assets/20949277/bd68c1d6-86c2-499c-b549-90f882c26c05

2023-06-16 19:00 UTC, Shadowfiend commented on background/redux-slices/utils/activities-utils.ts
> +type TransactionStatus = "pending" | "dropped" | "failed" | "completed"
> something is "a", if we remove "a" from the type above this becomes never

This is only an issue if `something` is never actually interacted with though, right? If things actually interact with it, we should get hit with errors at those points—and if we don't have such uses, then it's probably not a correctness issue… Open to more thinking here, but it feels like an artifact rather than a deep problem.

--------

So I've thought about this a little bit. enums, their mapping of variable names to strings to numbers, the fact that they're a language-level feature (which TypeScript generally doesn't do), and the fact that they have a long list of things to keep in mind in terms of how they work at runtime and compile time, etc, just feel like they're not worth the trouble.

For translations specifically, I think the type union ultimately helps us, because we can use it directly to reference i18n keys and we will know if we've hit all the i18n keys. We can get something similar with enum types if we set them all as explicit strings, but to do that we have to repeat every value (the enum name and then the string value), in addition to referring to the underlying type union in a relatively arcane way.

Overall, enums represent extra layers of indirection between us and the raw values that we're passing around. They give us some small advantages, but I don't think they're worth the tradeoff.

With that said, I'm going to escalate here :grin: and suggest we add a linter rule to prohibit enums altogether! <_<

2023-06-29 06:44 UTC, VladUXUI commented
Tested this out, and overall looks good! i did however find a couple of things:
1 - When i speed up the transaction the gas setting isn't changed/updated (If custom gas is used for first transaction)
This should have a higher number than the previous tx.
2 - If something was inputed in custom, but custom is NOT the selection in gas, estimated network still says the custom amount.
3 - The transaction that is replaced sometimes gets stuck in "pending" in activity page, but when i click to open it, it says dropped
<img width="363" alt="image" src="https://github.com/tahowallet/extension/assets/80846886/a3e71471-bbaf-4001-96a2-15f9f0074d73">
<img width="356" alt="image" src="https://github.com/tahowallet/extension/assets/80846886/63763183-90a3-45ee-acad-e6e2240b957e">
4 - Can we change dropped to "replaced"? or alternatively don't show the dropped transaction
5 - When speeding up, the initial transaction get's dropped. And i see the message that tx failed to broadcast, this is strange behaviour because users will think it's for the transaction that was sped up.

2023-06-29 06:47 UTC, VladUXUI commented
Talked about this with @hyphenized, about gas settings behaviour.
![image](https://github.com/tahowallet/extension/assets/80846886/c2fa031c-b14e-450b-8e43-bd046d02beab)

2023-07-26 06:58 UTC, VladUXUI commented
A couple of the points above are still there.

- [ ] The dropped /replaced transaction is still showing up

<img width="364" alt="image" src="https://github.com/tahowallet/extension/assets/80846886/33058533-b327-43d7-8f62-643746bb6010">

- [ ] The estimated gas is not updated to reflect the gas in Gas settings
![image](https://github.com/tahowallet/extension/assets/80846886/3af91e1c-8894-440d-95e9-a795b396511b)

- [ ] There max gas error is no implemented, and the information provided "low" is not enough.

let's not ship this as is and we can come back to it later

2023-07-26 07:03 UTC, VladUXUI commented
A bigger issue here is the disconnect between what we show on estimate network and what we show in gas settings.
I think this needs another rethink from me

2023-07-27 01:51 UTC, Shadowfiend commented
Got it. Sounds like we need to put this fellow into stasis.

Because this is a bigger piece of work, I'd like to suggest landing the effort so far hidden behind its feature flag. Wdyt @hyphenized ?

2023-07-27 06:16 UTC, hyphenized commented
> Got it. Sounds like we need to put this fellow into stasis.
> 
> Because this is a bigger piece of work, I'd like to suggest landing the effort so far hidden behind its feature flag. Wdyt @hyphenized ?

Easiest might be to block gas settings customization and ship this or, merge this behind the feature flag and break down the problems left into issues. Gas settings set on the replacement transaction are being ignored now and that's causing an immediate drop so will have to take a look into what's happening 😕

2023-07-27 13:01 UTC, andreachapman commented
> I'd like to merge so we can stick to shifting focus this week, but agree on capturing issues.
> 
> Let's maybe ask QA to look at a build of this PR with feature flag disabled and confirm transaction flow looks good, spin up issues, and merge it in.

I'm happy to do some regression on this with the feature flag disabled. Do we think we'd get it into the coming release cut with the flag disabled? If so, I was just thinking that the regression for that effort would cover it. But if it's going to be separate that fine too, I can test with the disabled flag whenever, if needed.

2023-07-28 10:34 UTC, kkosiorowska requested changes
I did some quick tests before merging when feature flag is off. After a swap, the selected activity view shows an error.

https://github.com/tahowallet/extension/assets/23117945/8629730c-4ac7-4e46-b217-3ea2c1fc052c


<img width="1008" alt="Screenshot 2023-07-28 at 12 31 38" src="https://github.com/tahowallet/extension/assets/23117945/4ebd58b0-1982-462d-8286-ba1a1903419a">

2023-07-28 10:34 UTC, kkosiorowska commented on ui/components/Wallet/WalletActivityDetails.tsx
> +  const hasReplacementTx = replacementTransactions.some(
```suggestion
  const hasReplacementTx = replacementTransactions?.some(
```

2023-07-28 10:34 UTC, kkosiorowska commented on ui/components/Wallet/WalletActivityDetails.tsx
> +  const isReplacementTx = replacementTransactions.some(
```suggestion
  const isReplacementTx = replacementTransactions?.some(
```

2023-07-28 11:01 UTC, jagodarybacka reviewed
Looking at the scope of changes and how much of the most fragile parts of the codebase were changed and refactored I would say we should do full regression and exploratory tests here, on the branch, before merging it even in this state. 
I'd say if this has even the slightest chance of messing up with gas prices which can cost our users real money being burned for gas then we shouldn't rush to merge it.

2023-07-28 11:07 UTC, kkosiorowska commented
I found one more issue, we aren't able to send transaction for custom networks. 

https://github.com/tahowallet/extension/assets/23117945/ea41a024-6c18-402e-a0ef-1f0ae639834d

2023-07-28 12:47 UTC, Shadowfiend commented
Ok, rereading the description and skimming the contents again, it looks like maybe we went too far down a rabbit hole in one PR in that case. I think we should break out the work that got done (refactors, etc) into separate issues referencing this PR, close it, and then we can pick the package up when cycles become available and run the underlying changes through in separate PRs with some git elbow grease.

2023-07-28 14:46 UTC, closed without merging