Allow setting custom auto-lock timer
tahowallet/extension pull request #3477
Opened 2023-06-14 04:36 UTC by hyphenized

Closes #3471

Adds a dropdown on settings to allow changing the maximum amount of time the wallet can remain idle before locking signing. This new setting is updated through an async thunk which triggers an event to also handle the change on the keyring service. The data is persisted on preferences db and exposed through redux to the UI.

## Testing Env

```
SUPPORT_CUSTOM_AUTOLOCK=true
```

## To Test
- [ ] Import an account
- [ ] Lock and unlock your wallet
- [ ] Head to settings, change auto-lock time
- [ ] Change your system's date or change the options [here](https://github.com/tahowallet/extension/blob/be6fae78bd7949cd5e4d8f37c882152d00e8141d/ui/pages/Settings.tsx#L308), test that different time options work correctly
- [ ] If the wallet has been idle for 10 minutes and the current auto lock setting changes to from 15 minutes to 5, the wallet should lock itself.

2023-06-14 15:54 UTC, jagodarybacka reviewed
Haven't tested yet, some quick comments

2023-06-14 15:54 UTC, jagodarybacka commented on background/redux-slices/ui.ts
> +  // TODO: Switch to fixed set of values?
I think it is fine, we have the "switch" implemented on the UI side anyway

2023-06-14 17:41 UTC, Shadowfiend commented on background/services/keyring/index.ts
Yes let’s use that as base please. Should have said that earlier and not referenced main in the issue, sorry folks 😕

2023-06-14 17:42 UTC, Shadowfiend commented on background/redux-slices/ui.ts
> +  // TODO: Switch to fixed set of values?
Correct, I think the view is the only place we should keep these fixed, the rest of the code should be flexible. We can drop the TODO.

2023-06-14 19:22 UTC, hyphenized commented on background/services/keyring/index.ts
All good diff isn't that big

2023-06-16 15:16 UTC, jagodarybacka commented
Hmm, Github isn't running checks for PRs to non-main branches, there is a problem with nonexisting variable reference, I'll fix it quickly

2023-06-16 15:36 UTC, jagodarybacka commented
if we are dropping a flag for private keys then I think we can release this thing in the same release as well and we can omit the feature flag here 🤔

2023-06-16 16:12 UTC, jagodarybacka approved these changes
Updated with the newest main changes so we can QA it here. Overall looks wonderful! I think we can drop the flag 🏳️

2023-06-16 20:22 UTC, Shadowfiend requested changes
Left a couple of notes around naming, typing, and data flow.

2023-06-16 20:22 UTC, Shadowfiend commented on background/services/preferences/defaults.ts
> +export const DEFAULT_AUTOLOCK_TIMER = 60 * MINUTE
Let's use the term `interval` or `time` (as the previous variables used), a timer is a thing that keeps time, whereas this is just the interval we want to use for our timer.

2023-06-16 20:22 UTC, Shadowfiend commented on background/services/internal-signer/index.ts
> +  #internalAutoLockTimer: UNIXTime = DEFAULT_AUTOLOCK_TIMER
This isn't a timestamp, it's an interval, so we can let the type be inferred.

2023-06-16 20:22 UTC, Shadowfiend commented on ui/pages/Settings.tsx
> +  ]
Let's lift this to the top level and ALL_CAPS it as we've done with other constants we're referencing that don't rely on scope.

2023-06-16 20:22 UTC, Shadowfiend commented on ui/pages/Settings.tsx
> +  const settings: SettingsList = {
Any reason this isn't just an array? Doesn't look like we're using the key for anything.

It actually feels like we could straightforwardly use the key for i18n purposes, iterating `Object.entries` and skipping the `title` field, so we have a `{ [titleKey: string]: SettingsItem[] }`.

Not blocking ofc.

2023-06-19 02:33 UTC, hyphenized commented on ui/pages/Settings.tsx
> +  const settings: SettingsList = {
No reason but also didn't consider it blocking. We could use `Object.entries` but we'd have to do some casting since translations are typed and expect a valid dictionary key.

2023-06-19 09:20 UTC, jagodarybacka commented on ui/pages/Settings.tsx
> +  const settings: SettingsList = {
This is already changed here and on [Flashbots PR](https://github.com/tahowallet/extension/blob/39d1c9b3bf7b0479ce1d6652f8e4ff6642043fea/ui/pages/Settings.tsx) as it was causing conflicts, I think we should unify it separately from both PRs to make them all compatible

2023-06-20 20:31 UTC, Shadowfiend commented on ui/pages/Settings.tsx
> +  const settings: SettingsList = {
> We could use Object.entries but we'd have to do some casting since translations are typed and expect a valid dictionary key.

I hate this about `Object.entries` 🙃

2023-06-22 09:39 UTC, jagodarybacka commented
@hyphenized could you resolve conflicts? I can test it one more time and I think it will be good to go

2023-06-22 15:00 UTC, jagodarybacka commented
I realized we are not mentioning what unit we are using here, pretty obvious that these are minutes but maybe not 🤔 cc @VladUXUI 
![image](https://github.com/tahowallet/extension/assets/20949277/cf6a1e20-da05-4878-b19a-0a62fb394642)

2023-06-23 08:26 UTC, jagodarybacka approved these changes
Works fine ✅

2023-06-23 08:27 UTC, merged