Flip updated dApp connections flag
tahowallet/extension pull request #3492
Opened 2023-06-21 19:09 UTC by Shadowfiend

cc @VladUXUI for design QA

2023-06-22 13:36 UTC, VladUXUI commented
Couple of non blocking small bits. Happy to have these as a ticket for next sprint.

- [ ] Dapp connection box is still using the old image. For consistency let's use the one that we are using in sign tx information box.

<img width="320" alt="image" src="https://github.com/tahowallet/extension/assets/80846886/9e967f2c-1a1b-43c6-9be1-d41fca2c40f9">
<img width="320" alt="image" src="https://github.com/tahowallet/extension/assets/80846886/1141370a-bf93-4869-93cb-7ae6743ce290">
 
 It doesn't need to be clickable
 

- [ ]  Couple of copy updates for this box

- Dap Connection = Website connections (title)
- How to connect to dapps = How to connect to websites
- Set Taho as default = Connect using Taho
- Click “connect to wallet” in a dapp = Click “connect” on a website

2023-06-23 19:16 UTC, Shadowfiend commented
This fellow should be ready.

2023-06-24 18:08 UTC, Shadowfiend commented
Trying to fix the failing e2e tests here led me to an issue that @hyphenized caught @ https://github.com/tahowallet/extension/pull/3462#discussion_r1230296367 . Need to fix that one as it will trigger anytime the user tries to connect to Taho as Taho (rather than as default) if they have Taho-as-default turned off (by auto-closing the dApp connection popup whoops).

2023-06-26 21:16 UTC, Shadowfiend commented
Ok, this should be ready again.

2023-06-29 08:02 UTC, michalinacienciala commented
@Shadowfiend, what about that removal of the connection banner from the swap screen? Are we leaving this at it is?

2023-06-29 10:07 UTC, Shadowfiend commented
Yep, remaining for now and left for future cleanup.

2023-06-30 04:21 UTC, VladUXUI commented
@hyphenized since you are feature buddy here, can you please review this PR?

2023-07-03 17:44 UTC, hyphenized requested changes
Works well! Found a small issue: when the wallet is not set as default, using the default wallet toggler twice in the connection popup opens a duplicate connect page.

2023-07-03 17:44 UTC, hyphenized commented on e2e-tests/dapp-connect.spec.ts
> +    const bgLocator = popupPage.locator(".bg")
Can we target the "void space" button instead? Something like this should work:

```ts
        popupPage
        .getByRole("button", { name: "Background close" })
        .click()
```

2023-07-03 17:44 UTC, hyphenized commented on e2e-tests/dapp-connect.spec.ts
> +    await dappPage.goto("https://swap.cow.fi/")
Probably worth running one small dApp along hardhat for some standard tests of this kind

2023-07-05 17:21 UTC, Shadowfiend commented
Updated the last bullet to reference app.eigenlayer.xyz instead of .com.

2023-07-05 17:22 UTC, Shadowfiend commented on e2e-tests/dapp-connect.spec.ts
> +    await dappPage.goto("https://swap.cow.fi/")
Would really love to avoid more stuff we have to maintain tbh, but agree this is a pretty kludgey way to do it.

2023-07-05 17:22 UTC, Shadowfiend commented on e2e-tests/dapp-connect.spec.ts
> +    const bgLocator = popupPage.locator(".bg")
I think that was my original approach and then I ran into issues that I thought were related but ultimately weren't, and then never changed it back. I'll poke at it.

2023-07-06 02:32 UTC, Shadowfiend commented on e2e-tests/dapp-connect.spec.ts
> +    const bgLocator = popupPage.locator(".bg")
https://github.com/tahowallet/extension/pull/3492/commits/220a0b8dadd72adbe3798605efce19033f4c029f

2023-07-06 02:35 UTC, Shadowfiend commented
> when the wallet is not set as default, using the default wallet toggler twice in the connection popup opens a duplicate connect page

This is fixed. I also made it so the wallet will correctly auto-close in this scenario.

The remaining edge case here is:
- If Taho is the only installed wallet.
- And Taho starts as non-default.
- And the user sets Taho as default in the dApp Connection popup.
- And the user then switches Taho back to non-default.
- Then Taho will auto-close and automatically reject the connection request, instead of continuing to wait for the user to hit Connect or Reject.

This seems vanishingly unlikely, and I suggest we don't spend any time trying to fix it unless we get a lot of user confusion, even though my engineering brain wants to solve it.

2023-07-08 06:57 UTC, hyphenized approved these changes

2023-07-08 06:59 UTC, merged