Refactor of terms for verified/unverified assets
tahowallet/extension pull request #3528
Opened 2023-07-05 09:33 UTC by kkosiorowska

2023-07-06 14:15 UTC, jagodarybacka reviewed
I would vote to write down in an RFB or in some other obvious place, in plain English, what we mean by `verified` `trusted` `baselineTrusted` or so. I know there are already comments in the `asset-utils` but I think it would be nice to have a glossary somewhere.

2023-07-06 14:15 UTC, jagodarybacka commented on background/redux-slices/selectors/0xSwapSelectors.ts
> +          (!isEnabled(FeatureFlags.SUPPORT_UNVERIFIED_ASSET) ||
Can we set up a PR that will remove the flag? That will further simplify the logic in many places

2023-07-06 20:26 UTC, hyphenized requested changes
Code looks great, left some suggestions. Will give it a test run shortly

2023-07-06 20:26 UTC, hyphenized commented on background/redux-slices/utils/asset-utils.ts
> +  }
Going to suggest that we remove `undefined` from these functions as it's going to be confusing and bug prone the fact that `!isUntrustedAsset` can't be used interchangeably as `isTrustedAsset`.

e.g.
```ts
  isUntrustedAsset(trustedAsset) => false
  !isUntrustedAsset(trustedAsset) => true
  isUntrustedAsset(undefined) => false
  !isUntrustedAsset(undefined) => true // `undefined` is not a trusted asset
```

2023-07-06 20:26 UTC, hyphenized commented on ui/components/Wallet/AssetListItem/CommonAssetListItem.tsx
> +  const isUntrusted = isUntrustedAsset(assetAmount.asset)
If untrusted assets are now custom assets that haven't been verified, then this will show prices for verified custom assets right?

2023-07-06 20:26 UTC, hyphenized commented on ui/pages/Send.tsx
> +          isTrustedAsset(assetAmount.asset))
This looks much better than `canBeUsedForTransaction` 👌

2023-07-06 20:26 UTC, hyphenized commented on ui/utils/swap.ts
> +          isTrustedAsset(assetAmount.asset))
We're allowing swapping for custom assets that are verified?

2023-07-06 20:26 UTC, hyphenized commented on ui/pages/SingleAsset.tsx
> +    : false
If an asset is not trusted, then it must be a custom asset that has not been verified, hence we should be able to refactor this to:

```suggestion
const showVerificationButton =
    isEnabled(FeatureFlags.SUPPORT_UNVERIFIED_ASSET) && !isTrusted
```

2023-07-06 20:26 UTC, hyphenized commented on ui/pages/SingleAsset.tsx
> +    : false
```suggestion
  const showVerifiedLabel =
    isEnabled(FeatureFlags.SUPPORT_UNVERIFIED_ASSET) && isVerified
```

Would also like to suggest inlining these checks if they're not too complex. Non-blocking

2023-07-07 02:24 UTC, Shadowfiend commented on background/redux-slices/selectors/0xSwapSelectors.ts
> +          (!isEnabled(FeatureFlags.SUPPORT_UNVERIFIED_ASSET) ||
Given we've had the feature flag kicking around, I'd be comfortable just killing it in this PR tbh.

2023-07-08 02:46 UTC, Shadowfiend commented on background/redux-slices/accounts.ts
> +      const canBeAggregated = isNetworkBaseAsset(asset) || isTrustedAsset(asset)
It feels like the whole concept of `canBeAggregated` can be nuked—do we need to compute a combined account balance for untrusted assets? It feels like before we run the `reduce` we should just do a `.filter(({ asset }) => isTrustedAsset(asset))`.

As far as I can tell, we use combined data to feed the overview page (which makes sense, since it's the only place where we would aggregate by symbol across chains—though that's probably not a strictly safe strategy), and the overview page never shows unverified assets.

2023-07-08 02:48 UTC, Shadowfiend commented on background/redux-slices/selectors/0xSwapSelectors.ts
> +        )
I'd be fine moving part after `&&` to another named constant (i.e. `const assetIsOnCurrentNetwork = isNetworkBase(...) || isSmartContractFungibleAsset(asset) && ...`) or even adding an `assetIsOnNetwork` helper, but nested ifs for simple boolean checks are going to be a no from me.

2023-07-08 03:46 UTC, Shadowfiend reviewed
Left some thoughts in four broad categories:

- Extra/slightly tweaked tests.
- Adjusted/clarified ways of expressing boolean expressions.
- Old man yells at cloud.
- Agreeing with @hyphenized lol.

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/utils/asset-utils.ts
> +  return false
This really just means `return asset?.metadata?.verified !== undefined && asset.metadata.verified`.

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/utils/asset-utils.ts
> +  }
Strong agreement with of this. Even though it's convenient to be able to pass `undefined`, these functions are security-sensitive and should do the minimum work we can squeeze into them.

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/utils/asset-utils.ts
> +  return !!asset?.metadata?.tokenLists?.length
`!!` really bugs me. I really feel like this would be clearer as:

```typescript
  const tokenListCount = asset?.metadata?.tokenLists?.length ?? 0

  return tokenListCount > 0
```

That said, this both isn't blocking and if you disagree we don't have to discuss it further haha.

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +      expect(isBaselineTrustedAsset(asset)).toBeTruthy()
For all of these, we're specifically looking for `toBe(true)` and `toBe(false)`, not truthy/falsy.

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +    test("should return false if is not a token list asset", () => {
```suggestion
    test("should return false if is neither a token list asset nor a network base asset", () => {
```

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +    test("should return true if is a network base asset", () => {
Should add a test that we get `true` if it's both.

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +    test("should return true if is a verified asset", () => {
```suggestion
    test("should return true if asset is explicitly verified", () => {
```

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +    test("should return false if is a unverified asset", () => {
```suggestion
    test("should return false if asset is explicitly unverified", () => {
```

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +    })
These are really testing around “if it has no explicit verification state”. I would make one `test(...)` that checks network base asset, token list asset, and perhaps more directly one with `createSmartContractAsset({ metadata: { verified: undefined } })`.

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +      expect(isTrustedAsset(asset)).toBeTruthy()
We should add a check that it also returns false for an asset with no verification state, no token list, and that isn't a network base asset.

2023-07-08 03:46 UTC, Shadowfiend commented on ui/components/Wallet/AssetListItem/CommonAssetListItem.tsx
> +  const isUntrusted = isUntrustedAsset(assetAmount.asset)
I hope the answer is yes! :)

2023-07-08 03:46 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +          isTrustedAsset(assetAmount.asset))
Wait 'til the feature flag is killed!

2023-07-08 03:46 UTC, Shadowfiend commented on ui/pages/SingleAsset.tsx
> +    : false
I actually think we should skip our easy booleans and tunnel in here. We should show the verification button only if `verified` is `undefined`: `asset?.metadata?.verified === undefined`.

My reasoning here is that, on the off chance that the user somehow finds themselves (through a bug!) viewing the single asset page for an asset that they have explicitly marked as not verified, we don't want to make it look exactly like a page whose trust level we don't actually know.

In a perfect world we would have some sort of “⚠️ Asset is not trusted” thing in the UI, but that's (1) out of scope here and (2),again, if they're viewing this asset page it means we've had a bug since we remove explicitly unverified assets from all lists that might lead you to this page.

2023-07-08 03:46 UTC, Shadowfiend commented on ui/pages/SingleAsset.tsx
> +    : false
Agree, once the flag is dropped we can just drop `showVerifiedLabel` and use `isVerified` instead.

2023-07-08 03:46 UTC, Shadowfiend commented on ui/pages/SingleAsset.tsx
> +        {showVerifiedLabel && asset && isSmartContractFungibleAsset(asset) && (
I can't believe `asset` can be `undefined` here. We should really return early or show an error or throw or something if `asset` is undefined, way up at the top of the page rendering. I do now understand what led to `isVerifiedAsset` & co taking `undefined` though (let's still not do it!).

2023-07-08 03:46 UTC, Shadowfiend commented on ui/utils/swap.ts
> +          isTrustedAsset(assetAmount.asset))
No reason we wouldn't? These assets should be equivalent to token list assets in every way (in fact, as I've mentioned a few times, the right long-term way to track custom assets is probably *as* a token list, which would simplify a lot of the logic we're throwing around even further).

2023-07-08 03:46 UTC, Shadowfiend commented on background/redux-slices/selectors/0xSwapSelectors.ts
> +          (isBuiltInNetworkBaseAsset(asset, currentNetwork) ||
`isNetworkBaseAsset` is too broad—we want to explicitly filter out base assets for networks other than the current one.

That said, `isBuiltInNetworkBaseAsset` is a misnomer. We should rename it to `isBaseAssetForNetwork(asset, network)`.

2023-07-10 09:40 UTC, kkosiorowska commented on background/redux-slices/selectors/0xSwapSelectors.ts
> +          (!isEnabled(FeatureFlags.SUPPORT_UNVERIFIED_ASSET) ||
https://github.com/tahowallet/extension/pull/3528/commits/22ee963102b1f2248c53f0160fda380c7d4db899

2023-07-10 09:40 UTC, kkosiorowska commented on ui/pages/SingleAsset.tsx
> +    : false
https://github.com/tahowallet/extension/pull/3528/commits/22ee963102b1f2248c53f0160fda380c7d4db899

2023-07-10 09:41 UTC, kkosiorowska commented on ui/pages/Send.tsx
> +          isTrustedAsset(assetAmount.asset))
https://github.com/tahowallet/extension/pull/3528/commits/22ee963102b1f2248c53f0160fda380c7d4db899

2023-07-10 11:04 UTC, kkosiorowska commented on background/redux-slices/selectors/0xSwapSelectors.ts
> +          (isBuiltInNetworkBaseAsset(asset, currentNetwork) ||
https://github.com/tahowallet/extension/pull/3528/commits/6c0b10c259a9f8f422ed3032e05e24e31cb14342

2023-07-10 11:04 UTC, kkosiorowska commented on background/redux-slices/selectors/0xSwapSelectors.ts
> +        )
https://github.com/tahowallet/extension/pull/3528/commits/6c0b10c259a9f8f422ed3032e05e24e31cb14342

2023-07-10 11:25 UTC, Shadowfiend commented on ui/pages/SingleAsset.tsx
> +        {showVerifiedLabel && asset && isSmartContractFungibleAsset(asset) && (
(Btw this is 100% out of scope for the PR.)

2023-07-10 17:58 UTC, Shadowfiend commented on ui/pages/SingleAsset.tsx
> +            {!isVerified && !isTrusted && isSmartContractFungibleAsset(asset) && (
`!isTrusted` implies `!isVerified`, right?

2023-07-11 07:46 UTC, kkosiorowska commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +      expect(isBaselineTrustedAsset(asset)).toBeTruthy()
https://github.com/tahowallet/extension/pull/3528/commits/9a5cf2e6b7c2417deb66ed807c2f4fe3a46b72b3

2023-07-11 07:46 UTC, kkosiorowska commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +    test("should return false if is not a token list asset", () => {
https://github.com/tahowallet/extension/pull/3528/commits/9a5cf2e6b7c2417deb66ed807c2f4fe3a46b72b3

2023-07-11 07:46 UTC, kkosiorowska commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +    test("should return true if is a network base asset", () => {
https://github.com/tahowallet/extension/pull/3528/commits/9a5cf2e6b7c2417deb66ed807c2f4fe3a46b72b3

2023-07-11 07:46 UTC, kkosiorowska commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +    test("should return true if is a verified asset", () => {
https://github.com/tahowallet/extension/pull/3528/commits/9a5cf2e6b7c2417deb66ed807c2f4fe3a46b72b3

2023-07-11 07:47 UTC, kkosiorowska commented on background/redux-slices/utils/tests/asset-utils.unit.test.ts
> +    })
https://github.com/tahowallet/extension/pull/3528/commits/9a5cf2e6b7c2417deb66ed807c2f4fe3a46b72b3

2023-07-11 07:59 UTC, kkosiorowska commented on background/redux-slices/utils/asset-utils.ts
> +  }
https://github.com/tahowallet/extension/pull/3528/commits/c351ab0e88638ba2ae20943af1c35e536a7df049

2023-07-11 08:00 UTC, kkosiorowska commented on background/redux-slices/utils/asset-utils.ts
> +  return false
https://github.com/tahowallet/extension/pull/3528/commits/c351ab0e88638ba2ae20943af1c35e536a7df049

2023-07-11 08:00 UTC, kkosiorowska commented on background/redux-slices/utils/asset-utils.ts
> +  return !!asset?.metadata?.tokenLists?.length
https://github.com/tahowallet/extension/pull/3528/commits/c351ab0e88638ba2ae20943af1c35e536a7df049

2023-07-11 08:14 UTC, kkosiorowska commented on ui/pages/SingleAsset.tsx
> +        {showVerifiedLabel && asset && isSmartContractFungibleAsset(asset) && (
Let's fix it later in https://github.com/tahowallet/extension/issues/3543.

2023-07-11 09:09 UTC, kkosiorowska commented on ui/components/Wallet/AssetListItem/CommonAssetListItem.tsx
> +  const isUntrusted = isUntrustedAsset(assetAmount.asset)
Yes, the price should be shown for verified assets as well. [Here](https://github.com/tahowallet/extension/blob/4e83cca1e85901a2b666fc2d40e98c663d3ec956/ui/components/Wallet/AssetListItem/CommonAssetListItem.tsx#L88-L104) is the logic for displaying the price for the asset.  However, this should also be included in the fix for fetching prices https://github.com/tahowallet/extension/pull/3508.

2023-07-11 09:16 UTC, kkosiorowska commented on ui/utils/swap.ts
> +          isTrustedAsset(assetAmount.asset))
> We're allowing swapping for custom assets that are verified?

Yes, after verification, the user should be able to swap and send such an asset. Confirmed with Vlad.

2023-07-11 11:59 UTC, kkosiorowska commented on background/redux-slices/accounts.ts
> +      const canBeAggregated = isNetworkBaseAsset(asset) || isTrustedAsset(asset)
https://github.com/tahowallet/extension/pull/3528/commits/07e7f6fd797042970474da08b9acffa7eb4c3ed2

2023-07-11 17:17 UTC, hyphenized reviewed
Tested and works well, there are still a couple of outstanding comments but otherwise looks good to go:

https://github.com/tahowallet/extension/pull/3528#discussion_r1256872328
https://github.com/tahowallet/extension/pull/3528#discussion_r1258658032

2023-07-11 17:18 UTC, hyphenized approved these changes

2023-07-11 17:41 UTC, Shadowfiend commented
I think neither of those are blocking and both see improvements already from the changes here; let's merge this fellow for the overall gains.

2023-07-11 19:37 UTC, merged

2023-07-13 10:48 UTC, kkosiorowska commented on ui/pages/SingleAsset.tsx
> +            {!isVerified && !isTrusted && isSmartContractFungibleAsset(asset) && (
There you are right. I overlooked that after the earlier changes.  :see_no_evil: