Don't treat assets in the token list as unverified
tahowallet/extension pull request #3534
Opened 2023-07-07 10:52 UTC by kkosiorowska

## What

During the new application installation, some of the assets in the token list were treated as unverified assets. 

Removal of the `discoveryTxHash` refresh logic. It is no longer needed. The change was to update the `discoveryTxHash` after the data migration, where `discoveryTxHash` was removed for all custom assets. This also resulted in the wrong adding of a `discoveryTxHash` for the asset in the token list. The change solves this issue.

## UI

**Before**

https://github.com/tahowallet/extension/assets/23117945/c8867a3f-0886-4b9a-a606-30eeba3bbd6b

**After**

https://github.com/tahowallet/extension/assets/23117945/3af9111f-22c9-4f61-a9a8-f6d0bbf2632e

## Testing

2023-07-07 13:51 UTC, jagodarybacka requested changes
Tested it manually and all is fine regarding token list's assets but none of the custom assets have discover tx hash after migration

2023-07-07 13:51 UTC, jagodarybacka commented on background/services/indexing/db.ts
> +      tx.table("customAssets")
We want `await` here right?

2023-07-07 14:22 UTC, kkosiorowska commented on background/services/indexing/db.ts
> +      tx.table("customAssets")
I'm not sure how best to save assets that we should remove from `customAssets`. `await` is needed here to get this info. If you have any suggestions on how to improve this, please let me know.

2023-07-07 14:29 UTC, hyphenized commented on background/services/indexing/db.ts
> +        .table("assetsToTrack")
Something to keep in mind here is that custom assets can also appear (and most should be due to balances syncing) in `assetsToTrack` so this is likely cleaning up custom assets as well. Additionally there should be no harm in leaving these assets in the custom assets table because, as mentioned in #3508, an asset might be discovered as a custom asset before being included in a token list. On the other hand if we still want to remove them, we should look at stored token list data and use that as the reference for removal.

2023-07-08 04:55 UTC, Shadowfiend commented
I'm struggling a little bit with the core motivation for this PR. With #3528 in place, we should be treating items as unverified only if they either have `verified: false | undefined` or they are not in a token list. All custom assets should have `verified: true` forcibly set, so it should be impossible for a custom *or* token list asset to be treated as unverified.

Is all of that right? Is the current behavior effectively fixed by #3528?

2023-07-13 11:36 UTC, kkosiorowska commented on background/services/indexing/db.ts
> +        .table("assetsToTrack")
@hyphenized  Yeah, good point. So what do you think about just removing the `discoveryTxHash` from assets that shouldn't have it from the `assetsToTrack` table?  The `customAssets` table will then be left as it is.

2023-07-13 11:49 UTC, kkosiorowska commented
> I'm struggling a little bit with the core motivation for this PR. With https://github.com/tahowallet/extension/pull/3528 in place, we should be treating items as unverified only if they either have verified: false | undefined or they are not in a token list. All custom assets should have verified: true forcibly set, so it should be impossible for a custom or token list asset to be treated as unverified.
> Is all of that right? Is the current behavior effectively fixed by https://github.com/tahowallet/extension/pull/3528?

Yes, everything is fine. The issue has been fixed [here](https://github.com/tahowallet/extension/pull/3491/files#diff-b0e4a7036b74ef74bb2061264a7470aa9dc941d5bb0b326556464bb28480fc80L703-R726). There isn't need to hold this PR open. Let's close it and, if there is a need for possible changes, let's do it in another PR.

2023-07-13 11:49 UTC, closed without merging