Support video avatars
tahowallet/extension pull request #3700
Opened 2023-12-14 09:03 UTC by xpaczka

Resolves #3688

2023-12-14 11:02 UTC, michalinacienciala commented
Looks that something is off about the default doggos avatars - they look zoomed in:
![image](https://github.com/tahowallet/extension/assets/78352137/c6059aba-fade-484d-b116-a25bf4095920)

2023-12-15 10:09 UTC, jagodarybacka requested changes

2023-12-15 10:58 UTC, michalinacienciala commented
The failures in the tests are caused by a known issue: https://github.com/tahowallet/extension/issues/3675.
In the tests we're first mark `BANANA` token as trusted and later remove it from the token list. The test expects to not see the BANANA token on the list after that, but due to the bug the token reappears on the list.
This may not always be failing, as sometimes it takes longer and sometimes shorter for the deleted asset to reappear.

2023-12-18 09:51 UTC, jagodarybacka requested changes

2023-12-18 09:51 UTC, jagodarybacka commented on background/redux-slices/migrations/to-36.ts
> +                  avatarType?: string
old state shouldn't have `avatarType` because this is actually the field we just added in this PR right?

2023-12-18 09:51 UTC, jagodarybacka commented on background/redux-slices/migrations/to-36.ts
> +    assets: [],
why we are resetting assets?

2023-12-18 09:51 UTC, jagodarybacka commented on background/redux-slices/migrations/to-36.ts
> +          const fileTypeResponse = await fetch(avatarURL, { method: "HEAD" })
Hmm I don't think this will work correctly because we are not waiting for results here at all, script will continue sync execution and will deserialize the preloaded state without waiting for these fetches. Actually, now I'm even thinking that we shouldn't even do it here at all - migrations should be working fast and be deterministic 🤔 Sorry about making it more confusing than it should be 😓 
Can we try to load the `avatarType` when the actual avatar is being loaded on the frontend side?

2023-12-18 14:45 UTC, jagodarybacka approved these changes
Looks 🔥 
![image](https://github.com/tahowallet/extension/assets/20949277/505da6c0-eaa1-44f5-94a4-77798a671e7e)

2023-12-18 14:48 UTC, merged