Redux Redux: A few QOL fixes + Manifest v3
tahowallet/extension pull request #3757
Opened 2024-12-23 20:43 UTC by Shadowfiend

Sundry:
- Manifest v3 support by moving window provider to an injected content script instead of the previous injection (h/t @hyphenized) as well as a version bump on webext-redux and a variety of other small changes to deal with related dependency updates.
- Improved logging details across the board.
- Common address copying logic.
- Added Open in Explorer to the account popup menu in the account slideover.
- Main is refactored to ReduxService, with store logic in its own file.
- Support for certain invocations of wallet_requestPermissions, the lack of which was breaking some sites.
- Fixes for tracking networks that were marked as inactive but were reactivated.
- Improvements for fallback behavior that was unnecessarily retrying connections.
- Fixes for RPC batching to avoid issues with excessive batch sizes.
- Improved redux store performance for certain actions that can be batched.

2024-12-23 21:52 UTC, mhluongo requested changes
Found a couple major issues that look like leftover local testing kludges.

Concept ACK, though, and around to review a fix

2024-12-23 21:52 UTC, mhluongo commented on background/features.ts
> +    const state = "" as string // localStorage.getItem(flagName)
This looks like a mistake?

2024-12-23 21:52 UTC, mhluongo commented on background/index.ts
> +import ReduxService from "./services/redux"
Glad to see the rename

2024-12-23 21:52 UTC, mhluongo commented on background/lib/logger.ts
> +    return "" // return window.localStorage.getItem(key) ?? ""
Also looks like a mistake

2024-12-23 21:52 UTC, mhluongo commented on background/lib/logger.ts
> +    // window.localStorage.setItem(key, value)
Boo

2024-12-23 21:52 UTC, mhluongo commented on background/lib/posthog.ts
> +      $current_url:
Interesting, does Posthog know what `service-worker` means?

2024-12-23 21:52 UTC, mhluongo commented on background/lib/priceOracle.ts
> +  if (assets.length > BATCH_SIZE) {
V nice

2024-12-23 21:52 UTC, mhluongo commented on background/lib/token-lists.ts
> +          tokenLists: Array.from(
I shudder to think how many there were before the unique

2024-12-23 21:52 UTC, mhluongo commented on background/services/abilities/index.ts
> +    // localStorage.setItem(this.ABILITY_TIME_KEY, Date.now().toString())
Another one @Shadowfiend

2024-12-23 21:52 UTC, mhluongo commented on background/services/abilities/index.ts
> +    const lastFetchTime = Date.now() // localStorage.getItem(this.ABILITY_TIME_KEY)
Mistake

2024-12-23 21:52 UTC, mhluongo commented on background/services/chain/asset-data-helper.ts
> +        "Problem resolving asset balances; network",
I'd rather see this in a template string but :shrug:

2024-12-23 21:52 UTC, mhluongo commented on background/services/indexing/index.ts
> +    loadingScope: "all" | "network" | "incremental"
I hate that we had to make this a thing, but it's a good solution

2024-12-23 21:52 UTC, mhluongo commented on background/services/provider-bridge/index.ts
> +      const [title, faviconUrl] = (event.request.params as unknown[]).slice(
Strange formatting here, not a fan

2024-12-23 21:52 UTC, mhluongo commented on src/background.ts
> +// FIXME: Temporary workaround to prevent the service worker from being suspended
We could use a follow-up issue for this as well as the other FIXME

2024-12-23 22:27 UTC, Shadowfiend commented on background/features.ts
> +    const state = "" as string // localStorage.getItem(flagName)
Not per se. I forgot to call out I disabled client side feature flags as storage access is completely different.

2024-12-23 22:29 UTC, Shadowfiend commented on background/lib/logger.ts
> +    return "" // return window.localStorage.getItem(key) ?? ""
This one is going to cost us logging for now but same deal, we have to use the async store which breaks most of the assumptions in here atm.

2024-12-23 22:29 UTC, Shadowfiend commented on background/lib/posthog.ts
> +      $current_url:
No more than anything else, this is just a string in posthog. Previously it was just the same URL always for the background script.

2024-12-23 22:32 UTC, Shadowfiend commented on background/services/chain/asset-data-helper.ts
> +        "Problem resolving asset balances; network",
Template strings stringify, separate params generally get interactive objects in the console.

2024-12-24 03:57 UTC, Shadowfiend commented on background/lib/token-lists.ts
> +          tokenLists: Array.from(
I cut my store in 4 I think by fixing this via asset updates.

2024-12-25 21:50 UTC, hyphenized reviewed
Mostly looks good, left a couple of comments but I definitely need to take a deeper look into the batch call tweak. Merry Christmas doggos

2024-12-25 21:50 UTC, hyphenized commented on manifest/manifest.json
> +    "pages": ["provider-bridge.js"]
I couldn't find if there's any benefit to adding this script under [sandbox](https://developer.chrome.com/docs/extensions/reference/manifest/sandbox)

2024-12-25 21:50 UTC, hyphenized commented on background/services/chain/serial-fallback-provider.ts
> +          pendingBatch?.length ?? pendingBatchSize ?? 1
A bit confused here, would appreciate if you could explain why we use the reference here to grab the most current length, instead of the stored pending batch size

2024-12-27 21:04 UTC, mhluongo commented
Okay, I better understand where we're at now — we're going to lose some functionality in the MV3 upgrade until we work through service worker issues, but time is of the essence.

Doing some local testing of our release candidate. Random things I've noticed

* Alt-T isn't working to open the extension. This might be because I have another (disabled) install
* Connecting to Curve (eg crvusd.curve.fi) is rough, though is always has been  
* Connecting to Aave, Threshold, and other dApps I use is way faster! I was a little shocked
* Connecting to Uniswap doesn't work at all :disappointed: and leads to an error page in the Taho UI

![image](https://github.com/user-attachments/assets/99be1bbd-df6f-4612-97b0-75cdc0f5bba2)

2024-12-27 21:07 UTC, mhluongo approved these changes
Would love :pray: follow up issues for the features that were effectively disabled by the MV3 upgrade. While I've seen a couple wallet connection issues, I think we should release and dp some follow-up QA to figure those out.

2024-12-27 21:07 UTC, merged

2024-12-27 21:47 UTC, Shadowfiend commented
> Alt-T isn't working to open the extension. This might be because I have another (disabled) install

This has been wobbly for a long time, for reasons that are still very unclear to me. It should just be set-it-and-forget-it.

> Connecting to Uniswap doesn't work at all 😞 and leads to an error page in the Taho UI

Will have a look at that. Would be good to implement EIP-6963 sooner rather than later, may or may not help. This may be related to https://github.com/tahowallet/extension/pull/3757/commits/5c35455459e61e47d8fa6a8685c9b9c46095c3e3 though.